\input texinfo @c permet à TeX de charger les macros nécessaires (-> \)
@setfilename rozofs 
@settitle @dfn{RozoFS} - User's Guide

@finalout

@c ***** summary and copyright
@include copyright.texi

@c ***** title, content and copyright (book)
@titlepage

@title @image{pics/rozofs, 3in, , , png}
@subtitle User's Guide
@author Sylvain David - @email{sylvain.david@@rozofs.com},
@author Pierre Evenou - @email{pierre.evenou@@rozofs.com},
@author Louis Le Gouriellec - @email{louis.legouriellec@@rozofs.com},
@author Didier Feron - @email{didier.feron@@rozofs.org},
@author Jean-Pierre Monchanin - @email{jean-pierre.monchanin@@rozofs.org}.

@c start copyright
@page
@vskip 0pt plus 1filll @c commande TeX
@insertcopying
@end titlepage

@contents

@c ***** document body
@c ***** 'Top' node and master menu
@ifnottex
@node Top
@top RozoFS - User's Guide

@insertcopying
@end ifnottex

@menu
* About this Guide::    some words about the guide
* About RozoFS::        global presentation of RozoFS
* Installing RozoFS::
* Setting up RozoFS::
* Working with RozoFS::
* Monitoring::
* Index::
@end menu

@include about_this_guide.texi
@include about_rozofs.texi
@include installing_rozofs.texi
@include setting_up_rozofs.texi
@include working_with_rozofs.texi
@include monitoring_rozofs.texi

@node Index, , Monitoring, Top
@unnumbered Index

@printindex cp

@bye
