@c *** Chapter [Working with RozoFS]
@node       Working with RozoFS, Monitoring, Setting up RozoFS, Top
@chapter    Working with RozoFS

@menu
* Manual Managing of RozoFS Services::
* Using the Rozo Console Manager::
@end menu

@c *** Section [Manual Managing of RozoFS Services]
@node       Manual Managing of RozoFS Services, Using the Rozo Console Manager, Working with RozoFS, Working with RozoFS
@section    Manual Managing of RozoFS Services
@ifnotdocbook
@cindex Managing daemons
@cindex Start daemons
@cindex Stop daemons
@end ifnotdocbook

@menu
* Starting and Stopping storaged Daemon::
* Starting and Stopping exportd Daemon::
* Accessing Data - Setting up rozofsmount Client::
@end menu

@c *** Subsection [Starting and Stopping storaged Daemon]
@node       Starting and Stopping storaged Daemon, Starting and Stopping exportd Daemon, Manual Managing of RozoFS Services, Manual Managing of RozoFS Services
@subsection Starting and Stopping storaged Daemon
@ifnotdocbook
@cindex Storaged
@cindex Storage node
@end ifnotdocbook

The storaged daemon starts with the following command:
@example
# /etc/init.d/rozofs-storaged start
@end example
@noindent To stop the daemon, the following command is used:
@example
# /etc/init.d/rozofs-storaged stop
@end example
@noindent To get the current status of the daemon, the following command is used:
@example
# /etc/init.d/rozofs-storaged status
@end example
@noindent To reload the storaged configuration file (@file{storage.conf}) after a
configuration changes, the following command is used:
@example
# /etc/init.d/rozofs-storaged reload
@end example
@noindent To automatically start the storaged daemon every time the system boots,
enterone of the following command lines.

@noindent For Red Hat based systems:
@example
# chkconfig rozofs-storaged on
@end example
@noindent For Debian based systems 
@example
# update-rc.d rozofs-storaged defaults
@end example
@noindent Systems Other than Red Hat and Debian:
@example
# echo "storaged" >> /etc/rc.local
@end example

@c *** Subsection [Starting and Stopping storaged Daemon]
@node       Starting and Stopping exportd Daemon, Accessing Data - Setting up rozofsmount Client, Starting and Stopping storaged Daemon, Manual Managing of RozoFS Services
@subsection Starting and Stopping exportd Daemon
@ifnotdocbook
@cindex Exportd
@end ifnotdocbook

The exportd daemon is started with the following command:
@example
# /etc/init.d/rozofs-exportd start
@end example

@noindent To stop the daemon, the following command is used:
@example
# /etc/init.d/rozofs-exportd stop
@end example

@noindent To get the current status of the daemon, the following command is used:
@example
# /etc/init.d/rozofs-exportd status
@end example

@noindent To reload the exportd configuration file (@file{export.conf}) after a
configuration changes, the following command is used:
@example
# /etc/init.d/rozofs-exportd reload
@end example

@noindent To automatically start the exportd daemon every time the system boots,
enter one of the following command line.

@noindent For Red Hat based systems:
@example
# chkconfig rozofs-exportd on
@end example
@noindent For Debian based systems 
@example
# update-rc.d rozofs-exportd defaults
@end example
@noindent Systems Other than Red Hat and Debian:
@example
# echo "exportd" >> /etc/rc.local
@end example

@c *** Subsection [Accessing Data - Setting up rozofsmount Client]
@node       Accessing Data - Setting up rozofsmount Client, , Starting and Stopping exportd Daemon, Manual Managing of RozoFS Services
@subsection Accessing Data - Setting up rozofsmount Client
@ifnotdocbook
@cindex Access data
@cindex rozofsmount
@end ifnotdocbook

After installing the rozofsmount (RozoFS Client), you have to mount the RozoFS
exported file system to access the data. 
Two methods are possible: mount manually or automatically.

To manually mount Rozo file system, use the following command:
@example
# rozofsmount -H EXPORT_IP -E EXPORT_PATH MOUNTDIR
@end example

For example, if the exported file system is:
@file{/srv/rozofs/exports/export_1} and @acronym{IP} address for export server
is 192.168.1.10:
@example
$ rozofsmount -H 192.168.1.10 -E
/srv/rozofs/exports/export_1 /mnt/rozofs/fs-1
@end example

To unmount the file system:
@example
$ umount /mnt/rozofs/fs-1
@end example

To automatically mount a Rozo file system, edit the @file{/etc/fstab} file and
add the following line:
@example
$ rozofsmount MOUNTDIR rozofs exporthost=EXPORT_IP,
exportpath=EXPORT_PATH,_netdev 0  0
@end example

For example, if the exported file system is @file{/srv/rozofs/exports/export_1}
and @acronym{IP} address for export server is 192.168.1.10 :
@example
$ rozofsmount /mnt/rozofs/fs1 rozofs\
$ exporthost=192.168.1.10,exportpath=/srv/rozofs/exports/export_1,_netdev
0\  0
@end example

@c *** Section [Using the Rozo Console Manager]
@node       Using the Rozo Console Manager, Get the List of Nodes Belonging to a Platform, Manual Managing of RozoFS Services, Working with RozoFS
@section    Using the Rozo Console Manager
@ifnotdocbook
@cindex Rozo Manager
@cindex Management
@end ifnotdocbook

@menu
* Get the List of Nodes Belonging to a Platform::
* Get the Status of a Platform::
* Stop and Start a Platform::
* View the Platform Configuration::
* Extend the Platform::
* Add an Export to the Platform::
@end menu

RozoFS comes with a command line utility called rozo that aims to automate the
@strong{management} process of a RozoFS platform. Its main purpose is to chain up
the operations required on remote nodes involved on a high level management task
such as stopping and starting the whole platform, add new nodes to the platform
in order to extend the capacity, add new exports on volume etc@dots{}

Rozo is fully independant of RozoFS daemons and processes and is not required
for a fully functional system but when installed aside RozoFS on each involved
nodes it greatly facilitates configuration as it takes care of all the unique
id generation of storage locations, clusters and so on. Despite not being a
monitoring tool, rozo can be however used to get easily a description of the
platform, its status and its configuration.

Rozo uses the running exportd configuration file as a basic platform knowledge,
you can use rozo on any nodes (even not involve in the platform).

You can have an overview of @command{rozo} capabilities and get the help you need by
using the rozo manual

@example
# man rozo
@end example

See below, examples of @command{rozo} usage for common management tasks on a 8 nodes
platform. Each command is launched on the running exportd node. 

@c *** Subsection [Get the List of Nodes Belonging to a Platform]
@node       Get the List of Nodes Belonging to a Platform, Get the Status of a Platform, Using the Rozo Console Manager, Using the Rozo Console Manager
@subsection Get the List of Nodes Belonging to a Platform
@ifnotdocbook
@cindex List of Nodes
@end ifnotdocbook

To get informations about all nodes in the platform and their roles.

@verbatim
root@node1:~# rozo node list -E 192.168.1.10
192.168.1.10:
- [EXPORTD]
192.168.1.101:
- [STORAGED, ROZOFSMOUNT]
192.168.1.102:
- [STORAGED, ROZOFSMOUNT]
192.168.1.103:
- [STORAGED, ROZOFSMOUNT]
192.168.1.104:
- [STORAGED, ROZOFSMOUNT]
@end verbatim

You can easily list nodes according to their roles (exportd, storaged or
rozofsmount) using the @option{-r} option.

@c *** Subsection [Get the Status of the Platform]
@node       Get the Status of a Platform, Stop and Start a Platform, Get the List of Nodes Belonging to a Platform, Using the Rozo Console Manager
@subsection Get the Status of a Platform
@ifnotdocbook
@cindex Status of platform
@end ifnotdocbook

To get an overview of the nodes: a RozoFS processes status.

@verbatim
root@node1:~# rozo node status -E 192.168.1.10
192.168.1.10:
- {EXPORTD: running}
192.168.1.101:
- {STORAGED: running}
- {ROZOFSMOUNT: running}
192.168.1.102:
- {STORAGED: running}
- {ROZOFSMOUNT: running}
192.168.1.103:
- {STORAGED: running}
- {ROZOFSMOUNT: running}
192.168.1.104:
- {STORAGED: running}
- {ROZOFSMOUNT: running}

@end verbatim
You can easily get nodes status according to their roles using the @option{-r}
option or get statuses for a specific node using the @option{-n} option.

@c *** Subsection [View the Platform Configuration]
@node       View the Platform Configuration, Extend the Platform, Stop and Start a Platform, Using the Rozo Console Manager
@subsection View the Platform Configuration
@ifnotdocbook
@cindex Overview of a platform
@cindex Platform overview
@end ifnotdocbook

@verbatim
root@node1:~# rozo node config -E 192.168.1.10
'NODE: 192.168.1.101':
- STORAGED:
  - INTERFACE:
    - {192.168.1.101: 41001}
  - STORAGE:
    - {'cid 1, sid 1': /srv/rozofs/storages/storage_1_1}
- ROZOFSMOUNT:
  - {node 192.168.1.10: /srv/rozofs/exports/export_1}
'NODE: 192.168.1.102':
- STORAGED:
  - INTERFACE:
    - {192.168.1.102: 41001}
  - STORAGE:
    - {'cid 1, sid 2': /srv/rozofs/storages/storage_1_2}
- ROZOFSMOUNT:
  - {node 192.168.1.10: /srv/rozofs/exports/export_1}
'NODE: 192.168.1.103':
- STORAGED:
  - INTERFACE:
    - {192.168.1.103: 41001}
  - STORAGE:
    - {'cid 1, sid 3': /srv/rozofs/storages/storage_1_3}
- ROZOFSMOUNT:
  - {node 192.168.1.10: /srv/rozofs/exports/export_1}
'NODE: 192.168.1.104':
- STORAGED:
  - INTERFACE:
    - {192.168.1.104: 41001}
  - STORAGE:
    - {'cid 1, sid 4': /srv/rozofs/storages/storage_1_4}
- ROZOFSMOUNT:
  - {node 192.168.1.10: /srv/rozofs/exports/export_1}
'NODE: 192.168.1.10':
- EXPORTD:
  - VOLUME:
    - volume 1:
      - cluster 1:
        - {sid 1: 192.168.1.101}
        - {sid 2: 192.168.1.102}
        - {sid 3: 192.168.1.103}
        - {sid 4: 192.168.1.104}
  - EXPORT:
      vid: 1
      root: /srv/rozofs/exports/export_1
      md5: ''
      squota: ''
      hquota: ''
@end verbatim

The output of rozo config let us know each node configuration according to its
role. We especially notice that this platform has one volume with one export
relying on it.

@c *** Subsection [Extend the Platform]
@node       Extend the Platform, Add an Export to the Platform, View the Platform Configuration, Using the Rozo Console Manager
@subsection Extend the Platform
@ifnotdocbook
@cindex Extend a platform
@cindex Add nodes
@end ifnotdocbook

Extend the platform is easy (add nodes) with the @command{rozo volume expand} command, for
example purpose we will add all the nodes already involved in volume 1

@verbatim
root@node1:~# rozo volume expand 192.168.1.201 \
                                 192.168.1.202 \
                                 192.168.1.203 \
                                 192.168.1.204 \
                                 -E 192.168.1.10 \
@end verbatim

As we added nodes without indicating the volume we want to expand,
@command{rozo} has created a new volume (with id 2) as illustrated in the rozo
volume list output extract below:

@verbatim
EXPORTD on 192.168.1.10:
- VOLUME 1:
  - CLUSTER 1:
    - {STORAGE 1: 192.168.1.101}
    - {STORAGE 2: 192.168.1.102}
    - {STORAGE 3: 192.168.1.103}
    - {STORAGE 4: 192.168.1.104}
- VOLUME 2:
  - CLUSTER 2:
    - {STORAGE 1: 192.168.1.201}
    - {STORAGE 2: 192.168.1.202}
    - {STORAGE 3: 192.168.1.203}
    - {STORAGE 4: 192.168.1.204}

@end verbatim

Indication of a volume id (e.g 1) would have resulted in the creation of a new
cluster in this volume.

@c *** Subsection [Add an Export to the Platform]
@node       Add an Export to the Platform, , Extend the Platform, Using the Rozo Console Manager
@subsection Add an Export to the Platform
@ifnotdocbook
@cindex Add an export
@cindex Delete an export
@end ifnotdocbook

rozo export and unexport commands manage the creation (and deletion) of new exports

@verbatim
root@node1:~# rozofs export create 1 -E 192.168.1.10
@end verbatim

This will create a new export on volume 1, and configure all nodes with a
rozofsmount role to mount this new export as illustrated in the @command{df} output
on one of the node.

@verbatim
root@node1:~# df | grep /mnt/rozofs
rozofs      4867164832      0 4867164832   0% /mnt/rozofs@node1/export_1
rozofs      4867164832      0 4867164832   0% /mnt/rozofs@node1/export_2
@end verbatim

