# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_profile', [dirname(__file__)])
        except ImportError:
            import _profile
            return _profile
        if fp is not None:
            try:
                _mod = imp.load_module('_profile', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _profile = swig_import_helper()
    del swig_import_helper
else:
    import _profile
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class epp_estat_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, epp_estat_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, epp_estat_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["eid"] = _profile.epp_estat_t_eid_set
    __swig_getmethods__["eid"] = _profile.epp_estat_t_eid_get
    if _newclass:eid = _swig_property(_profile.epp_estat_t_eid_get, _profile.epp_estat_t_eid_set)
    __swig_setmethods__["vid"] = _profile.epp_estat_t_vid_set
    __swig_getmethods__["vid"] = _profile.epp_estat_t_vid_get
    if _newclass:vid = _swig_property(_profile.epp_estat_t_vid_get, _profile.epp_estat_t_vid_set)
    __swig_setmethods__["bsize"] = _profile.epp_estat_t_bsize_set
    __swig_getmethods__["bsize"] = _profile.epp_estat_t_bsize_get
    if _newclass:bsize = _swig_property(_profile.epp_estat_t_bsize_get, _profile.epp_estat_t_bsize_set)
    __swig_setmethods__["blocks"] = _profile.epp_estat_t_blocks_set
    __swig_getmethods__["blocks"] = _profile.epp_estat_t_blocks_get
    if _newclass:blocks = _swig_property(_profile.epp_estat_t_blocks_get, _profile.epp_estat_t_blocks_set)
    __swig_setmethods__["bfree"] = _profile.epp_estat_t_bfree_set
    __swig_getmethods__["bfree"] = _profile.epp_estat_t_bfree_get
    if _newclass:bfree = _swig_property(_profile.epp_estat_t_bfree_get, _profile.epp_estat_t_bfree_set)
    __swig_setmethods__["files"] = _profile.epp_estat_t_files_set
    __swig_getmethods__["files"] = _profile.epp_estat_t_files_get
    if _newclass:files = _swig_property(_profile.epp_estat_t_files_get, _profile.epp_estat_t_files_set)
    __swig_setmethods__["ffree"] = _profile.epp_estat_t_ffree_set
    __swig_getmethods__["ffree"] = _profile.epp_estat_t_ffree_get
    if _newclass:ffree = _swig_property(_profile.epp_estat_t_ffree_get, _profile.epp_estat_t_ffree_set)
    def __init__(self): 
        this = _profile.new_epp_estat_t()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _profile.delete_epp_estat_t
    __del__ = lambda self : None;
epp_estat_t_swigregister = _profile.epp_estat_t_swigregister
epp_estat_t_swigregister(epp_estat_t)

class epp_sstat_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, epp_sstat_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, epp_sstat_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["sid"] = _profile.epp_sstat_t_sid_set
    __swig_getmethods__["sid"] = _profile.epp_sstat_t_sid_get
    if _newclass:sid = _swig_property(_profile.epp_sstat_t_sid_get, _profile.epp_sstat_t_sid_set)
    __swig_setmethods__["status"] = _profile.epp_sstat_t_status_set
    __swig_getmethods__["status"] = _profile.epp_sstat_t_status_get
    if _newclass:status = _swig_property(_profile.epp_sstat_t_status_get, _profile.epp_sstat_t_status_set)
    __swig_setmethods__["size"] = _profile.epp_sstat_t_size_set
    __swig_getmethods__["size"] = _profile.epp_sstat_t_size_get
    if _newclass:size = _swig_property(_profile.epp_sstat_t_size_get, _profile.epp_sstat_t_size_set)
    __swig_setmethods__["free"] = _profile.epp_sstat_t_free_set
    __swig_getmethods__["free"] = _profile.epp_sstat_t_free_get
    if _newclass:free = _swig_property(_profile.epp_sstat_t_free_get, _profile.epp_sstat_t_free_set)
    def __init__(self): 
        this = _profile.new_epp_sstat_t()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _profile.delete_epp_sstat_t
    __del__ = lambda self : None;
epp_sstat_t_swigregister = _profile.epp_sstat_t_swigregister
epp_sstat_t_swigregister(epp_sstat_t)

class epp_vstat_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, epp_vstat_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, epp_vstat_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["vid"] = _profile.epp_vstat_t_vid_set
    __swig_getmethods__["vid"] = _profile.epp_vstat_t_vid_get
    if _newclass:vid = _swig_property(_profile.epp_vstat_t_vid_get, _profile.epp_vstat_t_vid_set)
    __swig_setmethods__["bsize"] = _profile.epp_vstat_t_bsize_set
    __swig_getmethods__["bsize"] = _profile.epp_vstat_t_bsize_get
    if _newclass:bsize = _swig_property(_profile.epp_vstat_t_bsize_get, _profile.epp_vstat_t_bsize_set)
    __swig_setmethods__["bfree"] = _profile.epp_vstat_t_bfree_set
    __swig_getmethods__["bfree"] = _profile.epp_vstat_t_bfree_get
    if _newclass:bfree = _swig_property(_profile.epp_vstat_t_bfree_get, _profile.epp_vstat_t_bfree_set)
    __swig_setmethods__["nb_storages"] = _profile.epp_vstat_t_nb_storages_set
    __swig_getmethods__["nb_storages"] = _profile.epp_vstat_t_nb_storages_get
    if _newclass:nb_storages = _swig_property(_profile.epp_vstat_t_nb_storages_get, _profile.epp_vstat_t_nb_storages_set)
    __swig_setmethods__["sstats"] = _profile.epp_vstat_t_sstats_set
    __swig_getmethods__["sstats"] = _profile.epp_vstat_t_sstats_get
    if _newclass:sstats = _swig_property(_profile.epp_vstat_t_sstats_get, _profile.epp_vstat_t_sstats_set)
    def __init__(self): 
        this = _profile.new_epp_vstat_t()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _profile.delete_epp_vstat_t
    __del__ = lambda self : None;
epp_vstat_t_swigregister = _profile.epp_vstat_t_swigregister
epp_vstat_t_swigregister(epp_vstat_t)

class epp_profiler_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, epp_profiler_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, epp_profiler_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["uptime"] = _profile.epp_profiler_t_uptime_set
    __swig_getmethods__["uptime"] = _profile.epp_profiler_t_uptime_get
    if _newclass:uptime = _swig_property(_profile.epp_profiler_t_uptime_get, _profile.epp_profiler_t_uptime_set)
    __swig_setmethods__["now"] = _profile.epp_profiler_t_now_set
    __swig_getmethods__["now"] = _profile.epp_profiler_t_now_get
    if _newclass:now = _swig_property(_profile.epp_profiler_t_now_get, _profile.epp_profiler_t_now_set)
    __swig_setmethods__["vers"] = _profile.epp_profiler_t_vers_set
    __swig_getmethods__["vers"] = _profile.epp_profiler_t_vers_get
    if _newclass:vers = _swig_property(_profile.epp_profiler_t_vers_get, _profile.epp_profiler_t_vers_set)
    __swig_setmethods__["nb_volumes"] = _profile.epp_profiler_t_nb_volumes_set
    __swig_getmethods__["nb_volumes"] = _profile.epp_profiler_t_nb_volumes_get
    if _newclass:nb_volumes = _swig_property(_profile.epp_profiler_t_nb_volumes_get, _profile.epp_profiler_t_nb_volumes_set)
    __swig_setmethods__["vstats"] = _profile.epp_profiler_t_vstats_set
    __swig_getmethods__["vstats"] = _profile.epp_profiler_t_vstats_get
    if _newclass:vstats = _swig_property(_profile.epp_profiler_t_vstats_get, _profile.epp_profiler_t_vstats_set)
    __swig_setmethods__["nb_exports"] = _profile.epp_profiler_t_nb_exports_set
    __swig_getmethods__["nb_exports"] = _profile.epp_profiler_t_nb_exports_get
    if _newclass:nb_exports = _swig_property(_profile.epp_profiler_t_nb_exports_get, _profile.epp_profiler_t_nb_exports_set)
    __swig_setmethods__["estats"] = _profile.epp_profiler_t_estats_set
    __swig_getmethods__["estats"] = _profile.epp_profiler_t_estats_get
    if _newclass:estats = _swig_property(_profile.epp_profiler_t_estats_get, _profile.epp_profiler_t_estats_set)
    __swig_setmethods__["ep_mount"] = _profile.epp_profiler_t_ep_mount_set
    __swig_getmethods__["ep_mount"] = _profile.epp_profiler_t_ep_mount_get
    if _newclass:ep_mount = _swig_property(_profile.epp_profiler_t_ep_mount_get, _profile.epp_profiler_t_ep_mount_set)
    __swig_setmethods__["ep_umount"] = _profile.epp_profiler_t_ep_umount_set
    __swig_getmethods__["ep_umount"] = _profile.epp_profiler_t_ep_umount_get
    if _newclass:ep_umount = _swig_property(_profile.epp_profiler_t_ep_umount_get, _profile.epp_profiler_t_ep_umount_set)
    __swig_setmethods__["ep_statfs"] = _profile.epp_profiler_t_ep_statfs_set
    __swig_getmethods__["ep_statfs"] = _profile.epp_profiler_t_ep_statfs_get
    if _newclass:ep_statfs = _swig_property(_profile.epp_profiler_t_ep_statfs_get, _profile.epp_profiler_t_ep_statfs_set)
    __swig_setmethods__["ep_lookup"] = _profile.epp_profiler_t_ep_lookup_set
    __swig_getmethods__["ep_lookup"] = _profile.epp_profiler_t_ep_lookup_get
    if _newclass:ep_lookup = _swig_property(_profile.epp_profiler_t_ep_lookup_get, _profile.epp_profiler_t_ep_lookup_set)
    __swig_setmethods__["ep_getattr"] = _profile.epp_profiler_t_ep_getattr_set
    __swig_getmethods__["ep_getattr"] = _profile.epp_profiler_t_ep_getattr_get
    if _newclass:ep_getattr = _swig_property(_profile.epp_profiler_t_ep_getattr_get, _profile.epp_profiler_t_ep_getattr_set)
    __swig_setmethods__["ep_setattr"] = _profile.epp_profiler_t_ep_setattr_set
    __swig_getmethods__["ep_setattr"] = _profile.epp_profiler_t_ep_setattr_get
    if _newclass:ep_setattr = _swig_property(_profile.epp_profiler_t_ep_setattr_get, _profile.epp_profiler_t_ep_setattr_set)
    __swig_setmethods__["ep_readlink"] = _profile.epp_profiler_t_ep_readlink_set
    __swig_getmethods__["ep_readlink"] = _profile.epp_profiler_t_ep_readlink_get
    if _newclass:ep_readlink = _swig_property(_profile.epp_profiler_t_ep_readlink_get, _profile.epp_profiler_t_ep_readlink_set)
    __swig_setmethods__["ep_mknod"] = _profile.epp_profiler_t_ep_mknod_set
    __swig_getmethods__["ep_mknod"] = _profile.epp_profiler_t_ep_mknod_get
    if _newclass:ep_mknod = _swig_property(_profile.epp_profiler_t_ep_mknod_get, _profile.epp_profiler_t_ep_mknod_set)
    __swig_setmethods__["ep_mkdir"] = _profile.epp_profiler_t_ep_mkdir_set
    __swig_getmethods__["ep_mkdir"] = _profile.epp_profiler_t_ep_mkdir_get
    if _newclass:ep_mkdir = _swig_property(_profile.epp_profiler_t_ep_mkdir_get, _profile.epp_profiler_t_ep_mkdir_set)
    __swig_setmethods__["ep_unlink"] = _profile.epp_profiler_t_ep_unlink_set
    __swig_getmethods__["ep_unlink"] = _profile.epp_profiler_t_ep_unlink_get
    if _newclass:ep_unlink = _swig_property(_profile.epp_profiler_t_ep_unlink_get, _profile.epp_profiler_t_ep_unlink_set)
    __swig_setmethods__["ep_rmdir"] = _profile.epp_profiler_t_ep_rmdir_set
    __swig_getmethods__["ep_rmdir"] = _profile.epp_profiler_t_ep_rmdir_get
    if _newclass:ep_rmdir = _swig_property(_profile.epp_profiler_t_ep_rmdir_get, _profile.epp_profiler_t_ep_rmdir_set)
    __swig_setmethods__["ep_symlink"] = _profile.epp_profiler_t_ep_symlink_set
    __swig_getmethods__["ep_symlink"] = _profile.epp_profiler_t_ep_symlink_get
    if _newclass:ep_symlink = _swig_property(_profile.epp_profiler_t_ep_symlink_get, _profile.epp_profiler_t_ep_symlink_set)
    __swig_setmethods__["ep_rename"] = _profile.epp_profiler_t_ep_rename_set
    __swig_getmethods__["ep_rename"] = _profile.epp_profiler_t_ep_rename_get
    if _newclass:ep_rename = _swig_property(_profile.epp_profiler_t_ep_rename_get, _profile.epp_profiler_t_ep_rename_set)
    __swig_setmethods__["ep_readdir"] = _profile.epp_profiler_t_ep_readdir_set
    __swig_getmethods__["ep_readdir"] = _profile.epp_profiler_t_ep_readdir_get
    if _newclass:ep_readdir = _swig_property(_profile.epp_profiler_t_ep_readdir_get, _profile.epp_profiler_t_ep_readdir_set)
    __swig_setmethods__["ep_read_block"] = _profile.epp_profiler_t_ep_read_block_set
    __swig_getmethods__["ep_read_block"] = _profile.epp_profiler_t_ep_read_block_get
    if _newclass:ep_read_block = _swig_property(_profile.epp_profiler_t_ep_read_block_get, _profile.epp_profiler_t_ep_read_block_set)
    __swig_setmethods__["ep_write_block"] = _profile.epp_profiler_t_ep_write_block_set
    __swig_getmethods__["ep_write_block"] = _profile.epp_profiler_t_ep_write_block_get
    if _newclass:ep_write_block = _swig_property(_profile.epp_profiler_t_ep_write_block_get, _profile.epp_profiler_t_ep_write_block_set)
    __swig_setmethods__["ep_link"] = _profile.epp_profiler_t_ep_link_set
    __swig_getmethods__["ep_link"] = _profile.epp_profiler_t_ep_link_get
    if _newclass:ep_link = _swig_property(_profile.epp_profiler_t_ep_link_get, _profile.epp_profiler_t_ep_link_set)
    __swig_setmethods__["ep_setxattr"] = _profile.epp_profiler_t_ep_setxattr_set
    __swig_getmethods__["ep_setxattr"] = _profile.epp_profiler_t_ep_setxattr_get
    if _newclass:ep_setxattr = _swig_property(_profile.epp_profiler_t_ep_setxattr_get, _profile.epp_profiler_t_ep_setxattr_set)
    __swig_setmethods__["ep_getxattr"] = _profile.epp_profiler_t_ep_getxattr_set
    __swig_getmethods__["ep_getxattr"] = _profile.epp_profiler_t_ep_getxattr_get
    if _newclass:ep_getxattr = _swig_property(_profile.epp_profiler_t_ep_getxattr_get, _profile.epp_profiler_t_ep_getxattr_set)
    __swig_setmethods__["ep_removexattr"] = _profile.epp_profiler_t_ep_removexattr_set
    __swig_getmethods__["ep_removexattr"] = _profile.epp_profiler_t_ep_removexattr_get
    if _newclass:ep_removexattr = _swig_property(_profile.epp_profiler_t_ep_removexattr_get, _profile.epp_profiler_t_ep_removexattr_set)
    __swig_setmethods__["ep_listxattr"] = _profile.epp_profiler_t_ep_listxattr_set
    __swig_getmethods__["ep_listxattr"] = _profile.epp_profiler_t_ep_listxattr_get
    if _newclass:ep_listxattr = _swig_property(_profile.epp_profiler_t_ep_listxattr_get, _profile.epp_profiler_t_ep_listxattr_set)
    __swig_setmethods__["export_lv1_resolve_entry"] = _profile.epp_profiler_t_export_lv1_resolve_entry_set
    __swig_getmethods__["export_lv1_resolve_entry"] = _profile.epp_profiler_t_export_lv1_resolve_entry_get
    if _newclass:export_lv1_resolve_entry = _swig_property(_profile.epp_profiler_t_export_lv1_resolve_entry_get, _profile.epp_profiler_t_export_lv1_resolve_entry_set)
    __swig_setmethods__["export_lv2_resolve_path"] = _profile.epp_profiler_t_export_lv2_resolve_path_set
    __swig_getmethods__["export_lv2_resolve_path"] = _profile.epp_profiler_t_export_lv2_resolve_path_get
    if _newclass:export_lv2_resolve_path = _swig_property(_profile.epp_profiler_t_export_lv2_resolve_path_get, _profile.epp_profiler_t_export_lv2_resolve_path_set)
    __swig_setmethods__["export_lookup_fid"] = _profile.epp_profiler_t_export_lookup_fid_set
    __swig_getmethods__["export_lookup_fid"] = _profile.epp_profiler_t_export_lookup_fid_get
    if _newclass:export_lookup_fid = _swig_property(_profile.epp_profiler_t_export_lookup_fid_get, _profile.epp_profiler_t_export_lookup_fid_set)
    __swig_setmethods__["export_update_files"] = _profile.epp_profiler_t_export_update_files_set
    __swig_getmethods__["export_update_files"] = _profile.epp_profiler_t_export_update_files_get
    if _newclass:export_update_files = _swig_property(_profile.epp_profiler_t_export_update_files_get, _profile.epp_profiler_t_export_update_files_set)
    __swig_setmethods__["export_update_blocks"] = _profile.epp_profiler_t_export_update_blocks_set
    __swig_getmethods__["export_update_blocks"] = _profile.epp_profiler_t_export_update_blocks_get
    if _newclass:export_update_blocks = _swig_property(_profile.epp_profiler_t_export_update_blocks_get, _profile.epp_profiler_t_export_update_blocks_set)
    __swig_setmethods__["export_stat"] = _profile.epp_profiler_t_export_stat_set
    __swig_getmethods__["export_stat"] = _profile.epp_profiler_t_export_stat_get
    if _newclass:export_stat = _swig_property(_profile.epp_profiler_t_export_stat_get, _profile.epp_profiler_t_export_stat_set)
    __swig_setmethods__["export_lookup"] = _profile.epp_profiler_t_export_lookup_set
    __swig_getmethods__["export_lookup"] = _profile.epp_profiler_t_export_lookup_get
    if _newclass:export_lookup = _swig_property(_profile.epp_profiler_t_export_lookup_get, _profile.epp_profiler_t_export_lookup_set)
    __swig_setmethods__["export_getattr"] = _profile.epp_profiler_t_export_getattr_set
    __swig_getmethods__["export_getattr"] = _profile.epp_profiler_t_export_getattr_get
    if _newclass:export_getattr = _swig_property(_profile.epp_profiler_t_export_getattr_get, _profile.epp_profiler_t_export_getattr_set)
    __swig_setmethods__["export_setattr"] = _profile.epp_profiler_t_export_setattr_set
    __swig_getmethods__["export_setattr"] = _profile.epp_profiler_t_export_setattr_get
    if _newclass:export_setattr = _swig_property(_profile.epp_profiler_t_export_setattr_get, _profile.epp_profiler_t_export_setattr_set)
    __swig_setmethods__["export_link"] = _profile.epp_profiler_t_export_link_set
    __swig_getmethods__["export_link"] = _profile.epp_profiler_t_export_link_get
    if _newclass:export_link = _swig_property(_profile.epp_profiler_t_export_link_get, _profile.epp_profiler_t_export_link_set)
    __swig_setmethods__["export_mknod"] = _profile.epp_profiler_t_export_mknod_set
    __swig_getmethods__["export_mknod"] = _profile.epp_profiler_t_export_mknod_get
    if _newclass:export_mknod = _swig_property(_profile.epp_profiler_t_export_mknod_get, _profile.epp_profiler_t_export_mknod_set)
    __swig_setmethods__["export_mkdir"] = _profile.epp_profiler_t_export_mkdir_set
    __swig_getmethods__["export_mkdir"] = _profile.epp_profiler_t_export_mkdir_get
    if _newclass:export_mkdir = _swig_property(_profile.epp_profiler_t_export_mkdir_get, _profile.epp_profiler_t_export_mkdir_set)
    __swig_setmethods__["export_unlink"] = _profile.epp_profiler_t_export_unlink_set
    __swig_getmethods__["export_unlink"] = _profile.epp_profiler_t_export_unlink_get
    if _newclass:export_unlink = _swig_property(_profile.epp_profiler_t_export_unlink_get, _profile.epp_profiler_t_export_unlink_set)
    __swig_setmethods__["export_rmdir"] = _profile.epp_profiler_t_export_rmdir_set
    __swig_getmethods__["export_rmdir"] = _profile.epp_profiler_t_export_rmdir_get
    if _newclass:export_rmdir = _swig_property(_profile.epp_profiler_t_export_rmdir_get, _profile.epp_profiler_t_export_rmdir_set)
    __swig_setmethods__["export_symlink"] = _profile.epp_profiler_t_export_symlink_set
    __swig_getmethods__["export_symlink"] = _profile.epp_profiler_t_export_symlink_get
    if _newclass:export_symlink = _swig_property(_profile.epp_profiler_t_export_symlink_get, _profile.epp_profiler_t_export_symlink_set)
    __swig_setmethods__["export_readlink"] = _profile.epp_profiler_t_export_readlink_set
    __swig_getmethods__["export_readlink"] = _profile.epp_profiler_t_export_readlink_get
    if _newclass:export_readlink = _swig_property(_profile.epp_profiler_t_export_readlink_get, _profile.epp_profiler_t_export_readlink_set)
    __swig_setmethods__["export_rename"] = _profile.epp_profiler_t_export_rename_set
    __swig_getmethods__["export_rename"] = _profile.epp_profiler_t_export_rename_get
    if _newclass:export_rename = _swig_property(_profile.epp_profiler_t_export_rename_get, _profile.epp_profiler_t_export_rename_set)
    __swig_setmethods__["export_read"] = _profile.epp_profiler_t_export_read_set
    __swig_getmethods__["export_read"] = _profile.epp_profiler_t_export_read_get
    if _newclass:export_read = _swig_property(_profile.epp_profiler_t_export_read_get, _profile.epp_profiler_t_export_read_set)
    __swig_setmethods__["export_read_block"] = _profile.epp_profiler_t_export_read_block_set
    __swig_getmethods__["export_read_block"] = _profile.epp_profiler_t_export_read_block_get
    if _newclass:export_read_block = _swig_property(_profile.epp_profiler_t_export_read_block_get, _profile.epp_profiler_t_export_read_block_set)
    __swig_setmethods__["export_write_block"] = _profile.epp_profiler_t_export_write_block_set
    __swig_getmethods__["export_write_block"] = _profile.epp_profiler_t_export_write_block_get
    if _newclass:export_write_block = _swig_property(_profile.epp_profiler_t_export_write_block_get, _profile.epp_profiler_t_export_write_block_set)
    __swig_setmethods__["export_setxattr"] = _profile.epp_profiler_t_export_setxattr_set
    __swig_getmethods__["export_setxattr"] = _profile.epp_profiler_t_export_setxattr_get
    if _newclass:export_setxattr = _swig_property(_profile.epp_profiler_t_export_setxattr_get, _profile.epp_profiler_t_export_setxattr_set)
    __swig_setmethods__["export_getxattr"] = _profile.epp_profiler_t_export_getxattr_set
    __swig_getmethods__["export_getxattr"] = _profile.epp_profiler_t_export_getxattr_get
    if _newclass:export_getxattr = _swig_property(_profile.epp_profiler_t_export_getxattr_get, _profile.epp_profiler_t_export_getxattr_set)
    __swig_setmethods__["export_removexattr"] = _profile.epp_profiler_t_export_removexattr_set
    __swig_getmethods__["export_removexattr"] = _profile.epp_profiler_t_export_removexattr_get
    if _newclass:export_removexattr = _swig_property(_profile.epp_profiler_t_export_removexattr_get, _profile.epp_profiler_t_export_removexattr_set)
    __swig_setmethods__["export_listxattr"] = _profile.epp_profiler_t_export_listxattr_set
    __swig_getmethods__["export_listxattr"] = _profile.epp_profiler_t_export_listxattr_get
    if _newclass:export_listxattr = _swig_property(_profile.epp_profiler_t_export_listxattr_get, _profile.epp_profiler_t_export_listxattr_set)
    __swig_setmethods__["export_readdir"] = _profile.epp_profiler_t_export_readdir_set
    __swig_getmethods__["export_readdir"] = _profile.epp_profiler_t_export_readdir_get
    if _newclass:export_readdir = _swig_property(_profile.epp_profiler_t_export_readdir_get, _profile.epp_profiler_t_export_readdir_set)
    __swig_setmethods__["lv2_cache_put"] = _profile.epp_profiler_t_lv2_cache_put_set
    __swig_getmethods__["lv2_cache_put"] = _profile.epp_profiler_t_lv2_cache_put_get
    if _newclass:lv2_cache_put = _swig_property(_profile.epp_profiler_t_lv2_cache_put_get, _profile.epp_profiler_t_lv2_cache_put_set)
    __swig_setmethods__["lv2_cache_get"] = _profile.epp_profiler_t_lv2_cache_get_set
    __swig_getmethods__["lv2_cache_get"] = _profile.epp_profiler_t_lv2_cache_get_get
    if _newclass:lv2_cache_get = _swig_property(_profile.epp_profiler_t_lv2_cache_get_get, _profile.epp_profiler_t_lv2_cache_get_set)
    __swig_setmethods__["lv2_cache_del"] = _profile.epp_profiler_t_lv2_cache_del_set
    __swig_getmethods__["lv2_cache_del"] = _profile.epp_profiler_t_lv2_cache_del_get
    if _newclass:lv2_cache_del = _swig_property(_profile.epp_profiler_t_lv2_cache_del_get, _profile.epp_profiler_t_lv2_cache_del_set)
    __swig_setmethods__["volume_balance"] = _profile.epp_profiler_t_volume_balance_set
    __swig_getmethods__["volume_balance"] = _profile.epp_profiler_t_volume_balance_get
    if _newclass:volume_balance = _swig_property(_profile.epp_profiler_t_volume_balance_get, _profile.epp_profiler_t_volume_balance_set)
    __swig_setmethods__["volume_distribute"] = _profile.epp_profiler_t_volume_distribute_set
    __swig_getmethods__["volume_distribute"] = _profile.epp_profiler_t_volume_distribute_get
    if _newclass:volume_distribute = _swig_property(_profile.epp_profiler_t_volume_distribute_get, _profile.epp_profiler_t_volume_distribute_set)
    __swig_setmethods__["volume_stat"] = _profile.epp_profiler_t_volume_stat_set
    __swig_getmethods__["volume_stat"] = _profile.epp_profiler_t_volume_stat_get
    if _newclass:volume_stat = _swig_property(_profile.epp_profiler_t_volume_stat_get, _profile.epp_profiler_t_volume_stat_set)
    __swig_setmethods__["mdir_open"] = _profile.epp_profiler_t_mdir_open_set
    __swig_getmethods__["mdir_open"] = _profile.epp_profiler_t_mdir_open_get
    if _newclass:mdir_open = _swig_property(_profile.epp_profiler_t_mdir_open_get, _profile.epp_profiler_t_mdir_open_set)
    __swig_setmethods__["mdir_close"] = _profile.epp_profiler_t_mdir_close_set
    __swig_getmethods__["mdir_close"] = _profile.epp_profiler_t_mdir_close_get
    if _newclass:mdir_close = _swig_property(_profile.epp_profiler_t_mdir_close_get, _profile.epp_profiler_t_mdir_close_set)
    __swig_setmethods__["mdir_read_attributes"] = _profile.epp_profiler_t_mdir_read_attributes_set
    __swig_getmethods__["mdir_read_attributes"] = _profile.epp_profiler_t_mdir_read_attributes_get
    if _newclass:mdir_read_attributes = _swig_property(_profile.epp_profiler_t_mdir_read_attributes_get, _profile.epp_profiler_t_mdir_read_attributes_set)
    __swig_setmethods__["mdir_write_attributes"] = _profile.epp_profiler_t_mdir_write_attributes_set
    __swig_getmethods__["mdir_write_attributes"] = _profile.epp_profiler_t_mdir_write_attributes_get
    if _newclass:mdir_write_attributes = _swig_property(_profile.epp_profiler_t_mdir_write_attributes_get, _profile.epp_profiler_t_mdir_write_attributes_set)
    __swig_setmethods__["mreg_open"] = _profile.epp_profiler_t_mreg_open_set
    __swig_getmethods__["mreg_open"] = _profile.epp_profiler_t_mreg_open_get
    if _newclass:mreg_open = _swig_property(_profile.epp_profiler_t_mreg_open_get, _profile.epp_profiler_t_mreg_open_set)
    __swig_setmethods__["mreg_close"] = _profile.epp_profiler_t_mreg_close_set
    __swig_getmethods__["mreg_close"] = _profile.epp_profiler_t_mreg_close_get
    if _newclass:mreg_close = _swig_property(_profile.epp_profiler_t_mreg_close_get, _profile.epp_profiler_t_mreg_close_set)
    __swig_setmethods__["mreg_read_attributes"] = _profile.epp_profiler_t_mreg_read_attributes_set
    __swig_getmethods__["mreg_read_attributes"] = _profile.epp_profiler_t_mreg_read_attributes_get
    if _newclass:mreg_read_attributes = _swig_property(_profile.epp_profiler_t_mreg_read_attributes_get, _profile.epp_profiler_t_mreg_read_attributes_set)
    __swig_setmethods__["mreg_write_attributes"] = _profile.epp_profiler_t_mreg_write_attributes_set
    __swig_getmethods__["mreg_write_attributes"] = _profile.epp_profiler_t_mreg_write_attributes_get
    if _newclass:mreg_write_attributes = _swig_property(_profile.epp_profiler_t_mreg_write_attributes_get, _profile.epp_profiler_t_mreg_write_attributes_set)
    __swig_setmethods__["mreg_read_dist"] = _profile.epp_profiler_t_mreg_read_dist_set
    __swig_getmethods__["mreg_read_dist"] = _profile.epp_profiler_t_mreg_read_dist_get
    if _newclass:mreg_read_dist = _swig_property(_profile.epp_profiler_t_mreg_read_dist_get, _profile.epp_profiler_t_mreg_read_dist_set)
    __swig_setmethods__["mreg_write_dist"] = _profile.epp_profiler_t_mreg_write_dist_set
    __swig_getmethods__["mreg_write_dist"] = _profile.epp_profiler_t_mreg_write_dist_get
    if _newclass:mreg_write_dist = _swig_property(_profile.epp_profiler_t_mreg_write_dist_get, _profile.epp_profiler_t_mreg_write_dist_set)
    __swig_setmethods__["mslnk_open"] = _profile.epp_profiler_t_mslnk_open_set
    __swig_getmethods__["mslnk_open"] = _profile.epp_profiler_t_mslnk_open_get
    if _newclass:mslnk_open = _swig_property(_profile.epp_profiler_t_mslnk_open_get, _profile.epp_profiler_t_mslnk_open_set)
    __swig_setmethods__["mslnk_close"] = _profile.epp_profiler_t_mslnk_close_set
    __swig_getmethods__["mslnk_close"] = _profile.epp_profiler_t_mslnk_close_get
    if _newclass:mslnk_close = _swig_property(_profile.epp_profiler_t_mslnk_close_get, _profile.epp_profiler_t_mslnk_close_set)
    __swig_setmethods__["mslnk_read_attributes"] = _profile.epp_profiler_t_mslnk_read_attributes_set
    __swig_getmethods__["mslnk_read_attributes"] = _profile.epp_profiler_t_mslnk_read_attributes_get
    if _newclass:mslnk_read_attributes = _swig_property(_profile.epp_profiler_t_mslnk_read_attributes_get, _profile.epp_profiler_t_mslnk_read_attributes_set)
    __swig_setmethods__["mslnk_write_attributes"] = _profile.epp_profiler_t_mslnk_write_attributes_set
    __swig_getmethods__["mslnk_write_attributes"] = _profile.epp_profiler_t_mslnk_write_attributes_get
    if _newclass:mslnk_write_attributes = _swig_property(_profile.epp_profiler_t_mslnk_write_attributes_get, _profile.epp_profiler_t_mslnk_write_attributes_set)
    __swig_setmethods__["mslnk_read_link"] = _profile.epp_profiler_t_mslnk_read_link_set
    __swig_getmethods__["mslnk_read_link"] = _profile.epp_profiler_t_mslnk_read_link_get
    if _newclass:mslnk_read_link = _swig_property(_profile.epp_profiler_t_mslnk_read_link_get, _profile.epp_profiler_t_mslnk_read_link_set)
    __swig_setmethods__["mslnk_write_link"] = _profile.epp_profiler_t_mslnk_write_link_set
    __swig_getmethods__["mslnk_write_link"] = _profile.epp_profiler_t_mslnk_write_link_get
    if _newclass:mslnk_write_link = _swig_property(_profile.epp_profiler_t_mslnk_write_link_get, _profile.epp_profiler_t_mslnk_write_link_set)
    def __init__(self): 
        this = _profile.new_epp_profiler_t()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _profile.delete_epp_profiler_t
    __del__ = lambda self : None;
epp_profiler_t_swigregister = _profile.epp_profiler_t_swigregister
epp_profiler_t_swigregister(epp_profiler_t)

class spp_profiler_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, spp_profiler_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, spp_profiler_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["uptime"] = _profile.spp_profiler_t_uptime_set
    __swig_getmethods__["uptime"] = _profile.spp_profiler_t_uptime_get
    if _newclass:uptime = _swig_property(_profile.spp_profiler_t_uptime_get, _profile.spp_profiler_t_uptime_set)
    __swig_setmethods__["now"] = _profile.spp_profiler_t_now_set
    __swig_getmethods__["now"] = _profile.spp_profiler_t_now_get
    if _newclass:now = _swig_property(_profile.spp_profiler_t_now_get, _profile.spp_profiler_t_now_set)
    __swig_setmethods__["vers"] = _profile.spp_profiler_t_vers_set
    __swig_getmethods__["vers"] = _profile.spp_profiler_t_vers_get
    if _newclass:vers = _swig_property(_profile.spp_profiler_t_vers_get, _profile.spp_profiler_t_vers_set)
    __swig_setmethods__["stat"] = _profile.spp_profiler_t_stat_set
    __swig_getmethods__["stat"] = _profile.spp_profiler_t_stat_get
    if _newclass:stat = _swig_property(_profile.spp_profiler_t_stat_get, _profile.spp_profiler_t_stat_set)
    __swig_setmethods__["ports"] = _profile.spp_profiler_t_ports_set
    __swig_getmethods__["ports"] = _profile.spp_profiler_t_ports_get
    if _newclass:ports = _swig_property(_profile.spp_profiler_t_ports_get, _profile.spp_profiler_t_ports_set)
    __swig_setmethods__["remove"] = _profile.spp_profiler_t_remove_set
    __swig_getmethods__["remove"] = _profile.spp_profiler_t_remove_get
    if _newclass:remove = _swig_property(_profile.spp_profiler_t_remove_get, _profile.spp_profiler_t_remove_set)
    __swig_setmethods__["read"] = _profile.spp_profiler_t_read_set
    __swig_getmethods__["read"] = _profile.spp_profiler_t_read_get
    if _newclass:read = _swig_property(_profile.spp_profiler_t_read_get, _profile.spp_profiler_t_read_set)
    __swig_setmethods__["write"] = _profile.spp_profiler_t_write_set
    __swig_getmethods__["write"] = _profile.spp_profiler_t_write_get
    if _newclass:write = _swig_property(_profile.spp_profiler_t_write_get, _profile.spp_profiler_t_write_set)
    __swig_setmethods__["truncate"] = _profile.spp_profiler_t_truncate_set
    __swig_getmethods__["truncate"] = _profile.spp_profiler_t_truncate_get
    if _newclass:truncate = _swig_property(_profile.spp_profiler_t_truncate_get, _profile.spp_profiler_t_truncate_set)
    __swig_setmethods__["nb_io_processes"] = _profile.spp_profiler_t_nb_io_processes_set
    __swig_getmethods__["nb_io_processes"] = _profile.spp_profiler_t_nb_io_processes_get
    if _newclass:nb_io_processes = _swig_property(_profile.spp_profiler_t_nb_io_processes_get, _profile.spp_profiler_t_nb_io_processes_set)
    __swig_setmethods__["io_process_ports"] = _profile.spp_profiler_t_io_process_ports_set
    __swig_getmethods__["io_process_ports"] = _profile.spp_profiler_t_io_process_ports_get
    if _newclass:io_process_ports = _swig_property(_profile.spp_profiler_t_io_process_ports_get, _profile.spp_profiler_t_io_process_ports_set)
    def __init__(self): 
        this = _profile.new_spp_profiler_t()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _profile.delete_spp_profiler_t
    __del__ = lambda self : None;
spp_profiler_t_swigregister = _profile.spp_profiler_t_swigregister
spp_profiler_t_swigregister(spp_profiler_t)

class mpp_profiler_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, mpp_profiler_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, mpp_profiler_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["uptime"] = _profile.mpp_profiler_t_uptime_set
    __swig_getmethods__["uptime"] = _profile.mpp_profiler_t_uptime_get
    if _newclass:uptime = _swig_property(_profile.mpp_profiler_t_uptime_get, _profile.mpp_profiler_t_uptime_set)
    __swig_setmethods__["now"] = _profile.mpp_profiler_t_now_set
    __swig_getmethods__["now"] = _profile.mpp_profiler_t_now_get
    if _newclass:now = _swig_property(_profile.mpp_profiler_t_now_get, _profile.mpp_profiler_t_now_set)
    __swig_setmethods__["vers"] = _profile.mpp_profiler_t_vers_set
    __swig_getmethods__["vers"] = _profile.mpp_profiler_t_vers_get
    if _newclass:vers = _swig_property(_profile.mpp_profiler_t_vers_get, _profile.mpp_profiler_t_vers_set)
    __swig_setmethods__["rozofs_ll_lookup"] = _profile.mpp_profiler_t_rozofs_ll_lookup_set
    __swig_getmethods__["rozofs_ll_lookup"] = _profile.mpp_profiler_t_rozofs_ll_lookup_get
    if _newclass:rozofs_ll_lookup = _swig_property(_profile.mpp_profiler_t_rozofs_ll_lookup_get, _profile.mpp_profiler_t_rozofs_ll_lookup_set)
    __swig_setmethods__["rozofs_ll_forget"] = _profile.mpp_profiler_t_rozofs_ll_forget_set
    __swig_getmethods__["rozofs_ll_forget"] = _profile.mpp_profiler_t_rozofs_ll_forget_get
    if _newclass:rozofs_ll_forget = _swig_property(_profile.mpp_profiler_t_rozofs_ll_forget_get, _profile.mpp_profiler_t_rozofs_ll_forget_set)
    __swig_setmethods__["rozofs_ll_getattr"] = _profile.mpp_profiler_t_rozofs_ll_getattr_set
    __swig_getmethods__["rozofs_ll_getattr"] = _profile.mpp_profiler_t_rozofs_ll_getattr_get
    if _newclass:rozofs_ll_getattr = _swig_property(_profile.mpp_profiler_t_rozofs_ll_getattr_get, _profile.mpp_profiler_t_rozofs_ll_getattr_set)
    __swig_setmethods__["rozofs_ll_setattr"] = _profile.mpp_profiler_t_rozofs_ll_setattr_set
    __swig_getmethods__["rozofs_ll_setattr"] = _profile.mpp_profiler_t_rozofs_ll_setattr_get
    if _newclass:rozofs_ll_setattr = _swig_property(_profile.mpp_profiler_t_rozofs_ll_setattr_get, _profile.mpp_profiler_t_rozofs_ll_setattr_set)
    __swig_setmethods__["rozofs_ll_readlink"] = _profile.mpp_profiler_t_rozofs_ll_readlink_set
    __swig_getmethods__["rozofs_ll_readlink"] = _profile.mpp_profiler_t_rozofs_ll_readlink_get
    if _newclass:rozofs_ll_readlink = _swig_property(_profile.mpp_profiler_t_rozofs_ll_readlink_get, _profile.mpp_profiler_t_rozofs_ll_readlink_set)
    __swig_setmethods__["rozofs_ll_mknod"] = _profile.mpp_profiler_t_rozofs_ll_mknod_set
    __swig_getmethods__["rozofs_ll_mknod"] = _profile.mpp_profiler_t_rozofs_ll_mknod_get
    if _newclass:rozofs_ll_mknod = _swig_property(_profile.mpp_profiler_t_rozofs_ll_mknod_get, _profile.mpp_profiler_t_rozofs_ll_mknod_set)
    __swig_setmethods__["rozofs_ll_mkdir"] = _profile.mpp_profiler_t_rozofs_ll_mkdir_set
    __swig_getmethods__["rozofs_ll_mkdir"] = _profile.mpp_profiler_t_rozofs_ll_mkdir_get
    if _newclass:rozofs_ll_mkdir = _swig_property(_profile.mpp_profiler_t_rozofs_ll_mkdir_get, _profile.mpp_profiler_t_rozofs_ll_mkdir_set)
    __swig_setmethods__["rozofs_ll_unlink"] = _profile.mpp_profiler_t_rozofs_ll_unlink_set
    __swig_getmethods__["rozofs_ll_unlink"] = _profile.mpp_profiler_t_rozofs_ll_unlink_get
    if _newclass:rozofs_ll_unlink = _swig_property(_profile.mpp_profiler_t_rozofs_ll_unlink_get, _profile.mpp_profiler_t_rozofs_ll_unlink_set)
    __swig_setmethods__["rozofs_ll_rmdir"] = _profile.mpp_profiler_t_rozofs_ll_rmdir_set
    __swig_getmethods__["rozofs_ll_rmdir"] = _profile.mpp_profiler_t_rozofs_ll_rmdir_get
    if _newclass:rozofs_ll_rmdir = _swig_property(_profile.mpp_profiler_t_rozofs_ll_rmdir_get, _profile.mpp_profiler_t_rozofs_ll_rmdir_set)
    __swig_setmethods__["rozofs_ll_symlink"] = _profile.mpp_profiler_t_rozofs_ll_symlink_set
    __swig_getmethods__["rozofs_ll_symlink"] = _profile.mpp_profiler_t_rozofs_ll_symlink_get
    if _newclass:rozofs_ll_symlink = _swig_property(_profile.mpp_profiler_t_rozofs_ll_symlink_get, _profile.mpp_profiler_t_rozofs_ll_symlink_set)
    __swig_setmethods__["rozofs_ll_rename"] = _profile.mpp_profiler_t_rozofs_ll_rename_set
    __swig_getmethods__["rozofs_ll_rename"] = _profile.mpp_profiler_t_rozofs_ll_rename_get
    if _newclass:rozofs_ll_rename = _swig_property(_profile.mpp_profiler_t_rozofs_ll_rename_get, _profile.mpp_profiler_t_rozofs_ll_rename_set)
    __swig_setmethods__["rozofs_ll_open"] = _profile.mpp_profiler_t_rozofs_ll_open_set
    __swig_getmethods__["rozofs_ll_open"] = _profile.mpp_profiler_t_rozofs_ll_open_get
    if _newclass:rozofs_ll_open = _swig_property(_profile.mpp_profiler_t_rozofs_ll_open_get, _profile.mpp_profiler_t_rozofs_ll_open_set)
    __swig_setmethods__["rozofs_ll_link"] = _profile.mpp_profiler_t_rozofs_ll_link_set
    __swig_getmethods__["rozofs_ll_link"] = _profile.mpp_profiler_t_rozofs_ll_link_get
    if _newclass:rozofs_ll_link = _swig_property(_profile.mpp_profiler_t_rozofs_ll_link_get, _profile.mpp_profiler_t_rozofs_ll_link_set)
    __swig_setmethods__["rozofs_ll_read"] = _profile.mpp_profiler_t_rozofs_ll_read_set
    __swig_getmethods__["rozofs_ll_read"] = _profile.mpp_profiler_t_rozofs_ll_read_get
    if _newclass:rozofs_ll_read = _swig_property(_profile.mpp_profiler_t_rozofs_ll_read_get, _profile.mpp_profiler_t_rozofs_ll_read_set)
    __swig_setmethods__["rozofs_ll_write"] = _profile.mpp_profiler_t_rozofs_ll_write_set
    __swig_getmethods__["rozofs_ll_write"] = _profile.mpp_profiler_t_rozofs_ll_write_get
    if _newclass:rozofs_ll_write = _swig_property(_profile.mpp_profiler_t_rozofs_ll_write_get, _profile.mpp_profiler_t_rozofs_ll_write_set)
    __swig_setmethods__["rozofs_ll_flush"] = _profile.mpp_profiler_t_rozofs_ll_flush_set
    __swig_getmethods__["rozofs_ll_flush"] = _profile.mpp_profiler_t_rozofs_ll_flush_get
    if _newclass:rozofs_ll_flush = _swig_property(_profile.mpp_profiler_t_rozofs_ll_flush_get, _profile.mpp_profiler_t_rozofs_ll_flush_set)
    __swig_setmethods__["rozofs_ll_release"] = _profile.mpp_profiler_t_rozofs_ll_release_set
    __swig_getmethods__["rozofs_ll_release"] = _profile.mpp_profiler_t_rozofs_ll_release_get
    if _newclass:rozofs_ll_release = _swig_property(_profile.mpp_profiler_t_rozofs_ll_release_get, _profile.mpp_profiler_t_rozofs_ll_release_set)
    __swig_setmethods__["rozofs_ll_opendir"] = _profile.mpp_profiler_t_rozofs_ll_opendir_set
    __swig_getmethods__["rozofs_ll_opendir"] = _profile.mpp_profiler_t_rozofs_ll_opendir_get
    if _newclass:rozofs_ll_opendir = _swig_property(_profile.mpp_profiler_t_rozofs_ll_opendir_get, _profile.mpp_profiler_t_rozofs_ll_opendir_set)
    __swig_setmethods__["rozofs_ll_readdir"] = _profile.mpp_profiler_t_rozofs_ll_readdir_set
    __swig_getmethods__["rozofs_ll_readdir"] = _profile.mpp_profiler_t_rozofs_ll_readdir_get
    if _newclass:rozofs_ll_readdir = _swig_property(_profile.mpp_profiler_t_rozofs_ll_readdir_get, _profile.mpp_profiler_t_rozofs_ll_readdir_set)
    __swig_setmethods__["rozofs_ll_releasedir"] = _profile.mpp_profiler_t_rozofs_ll_releasedir_set
    __swig_getmethods__["rozofs_ll_releasedir"] = _profile.mpp_profiler_t_rozofs_ll_releasedir_get
    if _newclass:rozofs_ll_releasedir = _swig_property(_profile.mpp_profiler_t_rozofs_ll_releasedir_get, _profile.mpp_profiler_t_rozofs_ll_releasedir_set)
    __swig_setmethods__["rozofs_ll_fsyncdir"] = _profile.mpp_profiler_t_rozofs_ll_fsyncdir_set
    __swig_getmethods__["rozofs_ll_fsyncdir"] = _profile.mpp_profiler_t_rozofs_ll_fsyncdir_get
    if _newclass:rozofs_ll_fsyncdir = _swig_property(_profile.mpp_profiler_t_rozofs_ll_fsyncdir_get, _profile.mpp_profiler_t_rozofs_ll_fsyncdir_set)
    __swig_setmethods__["rozofs_ll_statfs"] = _profile.mpp_profiler_t_rozofs_ll_statfs_set
    __swig_getmethods__["rozofs_ll_statfs"] = _profile.mpp_profiler_t_rozofs_ll_statfs_get
    if _newclass:rozofs_ll_statfs = _swig_property(_profile.mpp_profiler_t_rozofs_ll_statfs_get, _profile.mpp_profiler_t_rozofs_ll_statfs_set)
    __swig_setmethods__["rozofs_ll_setxattr"] = _profile.mpp_profiler_t_rozofs_ll_setxattr_set
    __swig_getmethods__["rozofs_ll_setxattr"] = _profile.mpp_profiler_t_rozofs_ll_setxattr_get
    if _newclass:rozofs_ll_setxattr = _swig_property(_profile.mpp_profiler_t_rozofs_ll_setxattr_get, _profile.mpp_profiler_t_rozofs_ll_setxattr_set)
    __swig_setmethods__["rozofs_ll_getxattr"] = _profile.mpp_profiler_t_rozofs_ll_getxattr_set
    __swig_getmethods__["rozofs_ll_getxattr"] = _profile.mpp_profiler_t_rozofs_ll_getxattr_get
    if _newclass:rozofs_ll_getxattr = _swig_property(_profile.mpp_profiler_t_rozofs_ll_getxattr_get, _profile.mpp_profiler_t_rozofs_ll_getxattr_set)
    __swig_setmethods__["rozofs_ll_listxattr"] = _profile.mpp_profiler_t_rozofs_ll_listxattr_set
    __swig_getmethods__["rozofs_ll_listxattr"] = _profile.mpp_profiler_t_rozofs_ll_listxattr_get
    if _newclass:rozofs_ll_listxattr = _swig_property(_profile.mpp_profiler_t_rozofs_ll_listxattr_get, _profile.mpp_profiler_t_rozofs_ll_listxattr_set)
    __swig_setmethods__["rozofs_ll_removexattr"] = _profile.mpp_profiler_t_rozofs_ll_removexattr_set
    __swig_getmethods__["rozofs_ll_removexattr"] = _profile.mpp_profiler_t_rozofs_ll_removexattr_get
    if _newclass:rozofs_ll_removexattr = _swig_property(_profile.mpp_profiler_t_rozofs_ll_removexattr_get, _profile.mpp_profiler_t_rozofs_ll_removexattr_set)
    __swig_setmethods__["rozofs_ll_access"] = _profile.mpp_profiler_t_rozofs_ll_access_set
    __swig_getmethods__["rozofs_ll_access"] = _profile.mpp_profiler_t_rozofs_ll_access_get
    if _newclass:rozofs_ll_access = _swig_property(_profile.mpp_profiler_t_rozofs_ll_access_get, _profile.mpp_profiler_t_rozofs_ll_access_set)
    __swig_setmethods__["rozofs_ll_create"] = _profile.mpp_profiler_t_rozofs_ll_create_set
    __swig_getmethods__["rozofs_ll_create"] = _profile.mpp_profiler_t_rozofs_ll_create_get
    if _newclass:rozofs_ll_create = _swig_property(_profile.mpp_profiler_t_rozofs_ll_create_get, _profile.mpp_profiler_t_rozofs_ll_create_set)
    __swig_setmethods__["rozofs_ll_getlk"] = _profile.mpp_profiler_t_rozofs_ll_getlk_set
    __swig_getmethods__["rozofs_ll_getlk"] = _profile.mpp_profiler_t_rozofs_ll_getlk_get
    if _newclass:rozofs_ll_getlk = _swig_property(_profile.mpp_profiler_t_rozofs_ll_getlk_get, _profile.mpp_profiler_t_rozofs_ll_getlk_set)
    __swig_setmethods__["rozofs_ll_setlk"] = _profile.mpp_profiler_t_rozofs_ll_setlk_set
    __swig_getmethods__["rozofs_ll_setlk"] = _profile.mpp_profiler_t_rozofs_ll_setlk_get
    if _newclass:rozofs_ll_setlk = _swig_property(_profile.mpp_profiler_t_rozofs_ll_setlk_get, _profile.mpp_profiler_t_rozofs_ll_setlk_set)
    __swig_setmethods__["rozofs_ll_ioctl"] = _profile.mpp_profiler_t_rozofs_ll_ioctl_set
    __swig_getmethods__["rozofs_ll_ioctl"] = _profile.mpp_profiler_t_rozofs_ll_ioctl_get
    if _newclass:rozofs_ll_ioctl = _swig_property(_profile.mpp_profiler_t_rozofs_ll_ioctl_get, _profile.mpp_profiler_t_rozofs_ll_ioctl_set)
    def __init__(self): 
        this = _profile.new_mpp_profiler_t()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _profile.delete_mpp_profiler_t
    __del__ = lambda self : None;
mpp_profiler_t_swigregister = _profile.mpp_profiler_t_swigregister
mpp_profiler_t_swigregister(mpp_profiler_t)

class ep_client_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ep_client_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ep_client_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["host"] = _profile.ep_client_t_host_set
    __swig_getmethods__["host"] = _profile.ep_client_t_host_get
    if _newclass:host = _swig_property(_profile.ep_client_t_host_get, _profile.ep_client_t_host_set)
    __swig_setmethods__["port"] = _profile.ep_client_t_port_set
    __swig_getmethods__["port"] = _profile.ep_client_t_port_get
    if _newclass:port = _swig_property(_profile.ep_client_t_port_get, _profile.ep_client_t_port_set)
    __swig_setmethods__["rpcclt"] = _profile.ep_client_t_rpcclt_set
    __swig_getmethods__["rpcclt"] = _profile.ep_client_t_rpcclt_get
    if _newclass:rpcclt = _swig_property(_profile.ep_client_t_rpcclt_get, _profile.ep_client_t_rpcclt_set)
    def __init__(self): 
        this = _profile.new_ep_client_t()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _profile.delete_ep_client_t
    __del__ = lambda self : None;
ep_client_t_swigregister = _profile.ep_client_t_swigregister
ep_client_t_swigregister(ep_client_t)


def ep_client_initialize(*args):
  return _profile.ep_client_initialize(*args)
ep_client_initialize = _profile.ep_client_initialize

def ep_client_release(*args):
  return _profile.ep_client_release(*args)
ep_client_release = _profile.ep_client_release

def ep_client_get_profiler(*args):
  return _profile.ep_client_get_profiler(*args)
ep_client_get_profiler = _profile.ep_client_get_profiler

def ep_client_clear(*args):
  return _profile.ep_client_clear(*args)
ep_client_clear = _profile.ep_client_clear
class sp_client_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, sp_client_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, sp_client_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["host"] = _profile.sp_client_t_host_set
    __swig_getmethods__["host"] = _profile.sp_client_t_host_get
    if _newclass:host = _swig_property(_profile.sp_client_t_host_get, _profile.sp_client_t_host_set)
    __swig_setmethods__["port"] = _profile.sp_client_t_port_set
    __swig_getmethods__["port"] = _profile.sp_client_t_port_get
    if _newclass:port = _swig_property(_profile.sp_client_t_port_get, _profile.sp_client_t_port_set)
    __swig_setmethods__["rpcclt"] = _profile.sp_client_t_rpcclt_set
    __swig_getmethods__["rpcclt"] = _profile.sp_client_t_rpcclt_get
    if _newclass:rpcclt = _swig_property(_profile.sp_client_t_rpcclt_get, _profile.sp_client_t_rpcclt_set)
    def __init__(self): 
        this = _profile.new_sp_client_t()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _profile.delete_sp_client_t
    __del__ = lambda self : None;
sp_client_t_swigregister = _profile.sp_client_t_swigregister
sp_client_t_swigregister(sp_client_t)


def sp_client_initialize(*args):
  return _profile.sp_client_initialize(*args)
sp_client_initialize = _profile.sp_client_initialize

def sp_client_release(*args):
  return _profile.sp_client_release(*args)
sp_client_release = _profile.sp_client_release

def sp_client_get_profiler(*args):
  return _profile.sp_client_get_profiler(*args)
sp_client_get_profiler = _profile.sp_client_get_profiler

def sp_client_clear(*args):
  return _profile.sp_client_clear(*args)
sp_client_clear = _profile.sp_client_clear
class mp_client_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, mp_client_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, mp_client_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["host"] = _profile.mp_client_t_host_set
    __swig_getmethods__["host"] = _profile.mp_client_t_host_get
    if _newclass:host = _swig_property(_profile.mp_client_t_host_get, _profile.mp_client_t_host_set)
    __swig_setmethods__["port"] = _profile.mp_client_t_port_set
    __swig_getmethods__["port"] = _profile.mp_client_t_port_get
    if _newclass:port = _swig_property(_profile.mp_client_t_port_get, _profile.mp_client_t_port_set)
    __swig_setmethods__["rpcclt"] = _profile.mp_client_t_rpcclt_set
    __swig_getmethods__["rpcclt"] = _profile.mp_client_t_rpcclt_get
    if _newclass:rpcclt = _swig_property(_profile.mp_client_t_rpcclt_get, _profile.mp_client_t_rpcclt_set)
    def __init__(self): 
        this = _profile.new_mp_client_t()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _profile.delete_mp_client_t
    __del__ = lambda self : None;
mp_client_t_swigregister = _profile.mp_client_t_swigregister
mp_client_t_swigregister(mp_client_t)


def mp_client_initialize(*args):
  return _profile.mp_client_initialize(*args)
mp_client_initialize = _profile.mp_client_initialize

def mp_client_release(*args):
  return _profile.mp_client_release(*args)
mp_client_release = _profile.mp_client_release

def mp_client_get_profiler(*args):
  return _profile.mp_client_get_profiler(*args)
mp_client_get_profiler = _profile.mp_client_get_profiler

def mp_client_clear(*args):
  return _profile.mp_client_clear(*args)
mp_client_clear = _profile.mp_client_clear

def new_Uint16Array(*args):
  return _profile.new_Uint16Array(*args)
new_Uint16Array = _profile.new_Uint16Array

def delete_Uint16Array(*args):
  return _profile.delete_Uint16Array(*args)
delete_Uint16Array = _profile.delete_Uint16Array

def Uint16Array_getitem(*args):
  return _profile.Uint16Array_getitem(*args)
Uint16Array_getitem = _profile.Uint16Array_getitem

def Uint16Array_setitem(*args):
  return _profile.Uint16Array_setitem(*args)
Uint16Array_setitem = _profile.Uint16Array_setitem

def new_Uint64Array(*args):
  return _profile.new_Uint64Array(*args)
new_Uint64Array = _profile.new_Uint64Array

def delete_Uint64Array(*args):
  return _profile.delete_Uint64Array(*args)
delete_Uint64Array = _profile.delete_Uint64Array

def Uint64Array_getitem(*args):
  return _profile.Uint64Array_getitem(*args)
Uint64Array_getitem = _profile.Uint64Array_getitem

def Uint64Array_setitem(*args):
  return _profile.Uint64Array_setitem(*args)
Uint64Array_setitem = _profile.Uint64Array_setitem

def new_EppVstatArray(*args):
  return _profile.new_EppVstatArray(*args)
new_EppVstatArray = _profile.new_EppVstatArray

def delete_EppVstatArray(*args):
  return _profile.delete_EppVstatArray(*args)
delete_EppVstatArray = _profile.delete_EppVstatArray

def EppVstatArray_getitem(*args):
  return _profile.EppVstatArray_getitem(*args)
EppVstatArray_getitem = _profile.EppVstatArray_getitem

def EppVstatArray_setitem(*args):
  return _profile.EppVstatArray_setitem(*args)
EppVstatArray_setitem = _profile.EppVstatArray_setitem

def new_EppEstatArray(*args):
  return _profile.new_EppEstatArray(*args)
new_EppEstatArray = _profile.new_EppEstatArray

def delete_EppEstatArray(*args):
  return _profile.delete_EppEstatArray(*args)
delete_EppEstatArray = _profile.delete_EppEstatArray

def EppEstatArray_getitem(*args):
  return _profile.EppEstatArray_getitem(*args)
EppEstatArray_getitem = _profile.EppEstatArray_getitem

def EppEstatArray_setitem(*args):
  return _profile.EppEstatArray_setitem(*args)
EppEstatArray_setitem = _profile.EppEstatArray_setitem

def new_EppSstatArray(*args):
  return _profile.new_EppSstatArray(*args)
new_EppSstatArray = _profile.new_EppSstatArray

def delete_EppSstatArray(*args):
  return _profile.delete_EppSstatArray(*args)
delete_EppSstatArray = _profile.delete_EppSstatArray

def EppSstatArray_getitem(*args):
  return _profile.EppSstatArray_getitem(*args)
EppSstatArray_getitem = _profile.EppSstatArray_getitem

def EppSstatArray_setitem(*args):
  return _profile.EppSstatArray_setitem(*args)
EppSstatArray_setitem = _profile.EppSstatArray_setitem


