.\" Process this file with
.\" groff -man -Tascii rozo.1
.\"
.TH ROZO 1 "JULY 2013" Rozofs "User Manuals"
.SH NAME
rozo \- rozofs management tool
.SH SYNOPSIS
.B rozo
[\fB\-d\fP]
\fItopic
\fP[\fIoptions\fP]
\fIcommand
\fP[\fIoptions\fP]
.PP
.B rozo
\fB\-h\fP | \fB\-\-help\fP
[\fItopic\fP [\fIaction\fP]]
.PP
.B rozo
\fB\-V\fP | \fB\-\-version\fP
.PP
.SH DESCRIPTION
.B rozo
manages a
.BR rozofs (7)
platform.
.SS
General options:
.TP
\fB\-d\fP, \fB\-\-debug
set debugging on.
.TP
\fB\-h\fP, \fB\-\-help
display help and exit.
.TP
\fB\-V\fP, \fB\-\-version
display version information and exit.
.SH AGENT TOPIC
.B rozo agent
.I status \fP|\fI start \fP|\fI stop \fP|\fI restart
.SS status
.B rozo agent status
.TP
Get rozo agent status for this node.
.SS start
.B rozo agent start \fP[\fB\-p | \-\-pacemaker\fP] [\fIlistener\fP...]
.TP
\fPStart a rozo agent with the given \fIlistener\fP list. \fIlisterner\fP must be a subset of {exportd, storaged, rozofsmount}
.TP
\fB\-p\fP, \fB--pacemaker\fP
whenever
.BR exportd (8)
is managed by pacemaker.

.SS stop
.B rozo agent stop
.TP
Stop rozo agent for this node.

.SS restart
.B rozo agent restart \fP[\fB\-p | \-\-pacemaker\fP] [\fIlistener\fP...]
.TP
\fPStop any running rozo agent then start it with the given \fIlistener\fP
list. \fIlisterner\fP must be a subset of {exportd, storaged, rozofsmount}
.TP
\fB\-p\fP, \fB--pacemaker\fP
whenever
.BR exportd (8)
is managed by pacemaker.

.\""" rozo layout
.SH LAYOUT TOPIC
.B rozo layout
.I get\fP | \fIset\fP \fB\-E | \-\-exportd\fP \fIhost\fP 

.\" rozo layout get
.SS get
.B rozo layout get \fB\-E | \-\-exportd\fP \fIhost\fP 
.TP 
Get the storage \fIlayout\fP for this platform, see \fBexportd(8)\fP,
\fBrozofs(7)\fP. The \fIlayout\fP value should be 0, 1 or 2.
.TP
\fB\-E\fP, \fB--exportd \fP\fIhost
A running exportd hostname.

.\" rozo layout set
.SS set
.B rozo layout set \fIlayout\fP \fB\-E | \-\-exportd\fP \fIhost\fP
.TP 
Set the protection configuration for this platform according to the given \fIlayout\fP, see \fBexportd(8)\fP, \fBrozofs(7)\fP. The \fIlayout\fP value must be 0, 1 or 2.
.TP
\fB\-E\fP, \fB--exportd \fP\fIhost
A running exportd hostname.


.SH NODE TOPIC
.B rozo node
.I list\fP | \fIstatus\fP | \fIconfig\fP | \fIstart\fP | \fIstop\fP [\fB\-r | \-\-roles\fP \fIrole\fP...] \fB\-E | \-\-exportd\fP \fIhost\fP 

.\" rozo node list
.SS list
.B rozo node list [\fB\-r | \-\-roles\fP \fIrole\fP...] \fB\-E | \-\-exportd\fP \fIhost\fP 
.TP 
Display the list of nodes managed by this platform. Nodes are specified with their roles.
.TP
\fB\-E\fP, \fB--exportd \fP\fIhost
A running exportd hostname.
.TP 
\fB\-r | \-\-roles\fP\fI role\fP...
List of roles. Must be a subset of {exportd,storaged,rozofsmount}. Only nodes with these roles will be listed. If not set all nodes with all roles will be displayed.

.\" rozo node status
.SS status
.B rozo node status [\fB\-r | \-\-roles\fP \fIrole\fP...] [\fB\-n | \-\-nodes\fP \fInode\fP...] \fB\-E | \-\-exportd\fP \fIhost\fP 
.TP 
Display the list of node managed by this platform. Check the status of nodes and their associated RozoFS components. Nodes and roles can be set to filter the output. If none is specified, everything is displayed.
.TP
\fB\-E\fP, \fB--exportd \fP\fIhost
A running exportd hostname.
.TP
\fB\-r | \-\-roles\fP\fI role\fP... 
List of roles. Must be a subset of {exportd,storaged,rozofsmount}. Only nodes with these roles will be listed. If not set all nodes with all roles will be displayed.
.TP
\fB\-n | \-\-nodes\fP\fI node\fP...
List of node hostnames to be displayed. If not set all nodes of the platform will be displayed.

.\" rozo node config
.SS config
.B rozo node config [\fB\-r | \-\-roles\fP \fIrole\fP...] [\fB\-n | \-\-nodes\fP \fInode\fP...] \fB\-E | \-\-exportd\fP \fIhost\fP 
.TP 
Display the list of nodes managed by this platform. Check the status of nodes and their associated RozoFS components. Nodes and roles can be set to filter the output. If none is specified, everything is displayed.
.TP
\fB\-E\fP, \fB--exportd \fP\fIhost
A running exportd hostname.
.TP
\fB\-r | \-\-roles\fP\fI role\fP... 
List of roles. Must be a subset of {exportd,storaged,rozofsmount}. Only nodes with these roles will be listed. If not set all nodes with all roles will be displayed.
.TP
\fB\-n | \-\-nodes\fP\fI node\fP...
List of node hostnames to be displayed. If not set all nodes of the platform will be displayed.

.\" rozo node start
.SS start
.B rozo node start [\fB\-r | \-\-roles\fP \fIrole\fP...] [\fB\-n | \-\-nodes\fP \fInode\fP...] \fB\-E | \-\-exportd\fP \fIhost\fP 
.TP 
Start node services.
.TP
\fB\-E\fP, \fB\-\-exportd \fP\fIhost
A running exportd hostname.
.TP
\fB\-r\fP, \fB\-\-roles\fP\fI role\fP... 
List of roles. Must be a subset of {exportd,storaged,rozofsmount}. Only nodes with these roles will be listed. If not set all nodes with all roles will be displayed.
.TP
\fB\-n\fP, \fB\-\-nodes\fP\fI node(s)\fP,... 
List of node hostnames to be started. If not set all nodes of the platform will be started.

.\" rozo node stop
.SS stop
.B rozo node stop [\fB\-r |\-\-roles\fP \fIrole\fP...] [\fB\-n | \-\-nodes\fP \fInode\fP...] \fB\-E | \-\-exportd\fP \fIhost\fP 
.TP 
Stop node services.
.TP
\fB\-E\fP, \fB\-\-exportd \fP\fIhost
A running exportd hostname.
\fB\-r\fP, \fB\-\-roles\fP\fI role\fP... 
List of roles. Must be a subset of {exportd,storaged,rozofsmount}. Only nodes with these roles will be listed. If not set all nodes with all roles will be displayed.
.TP
\fB\-n\fP, \fB\-\-nodes\fP\fI node\fP...
List of node hostnames to be stopped. If not set all nodes of the platform
will be stopped.


.\""" rozo volume
.SH VOLUME TOPIC
.B rozo volume
.I list\fP | \fIstat\fP | \fIget\fP | \fIexpand\fP | \fIremove\fP \fB\-E | \-\-exportd\fP \fIhost\fP 

.\" rozo volume list
.SS list
.B rozo volume list \fB\-E | \-\-exportd\fP \fIhost\fP 
.TP 
Display the list of the volumes managed by this platform. Volumes contain clusters which contain storages.
.TP
\fB\-E\fP, \fB\-\-exportd \fP\fIhost
A running exportd hostname.

.\" rozo volume stat
.SS stat
.B rozo volume stat \fB\-E | \-\-exportd\fP \fIhost\fP 
.TP 
Display statistics about the volumes managed by this platform.
.TP
\fB\-E\fP, \fB\-\-exportd \fP\fIhost
A running exportd hostname.

.\" rozo volume get
.SS get
.B rozo volume get \fIvid\fP... \fB\-E | \-\-exportd\fP \fIhost\fP
.TP 
Display statistics about the volume according to the given \fIvid(s)\fP.
.TP
\fB\-E\fP, \fB\-\-exportd \fP\fIhost
A running exportd hostname.

.\" rozo volume expand
.SS expand
.B rozo volume expand [\fB\-v | \-\-vid\fP \fIvid\fP...] \fInode\fP...  \fB\-E | \-\-exportd\fP \fIhost\fP 
.TP 
Expand a volume relying on the given list of storage \fInode\fP hostnames. 
.TP
\fB\-E\fP, \fB\-\-exportd \fP\fIhost
A running exportd hostname.
.TP
\fB\-v\fP, \fB\-\-vid\fP \fIvid\fP...
List of the \fBvid\fP of the volumes to expand. If not set a new volume will be created.

.\" rozo volume remove
.SS remove
.B rozo volume remove \fIvid\fP... \fB\-E | \-\-exportd\fP \fIhost\fP 
.TP 
Remove a volume according to the given \fIvid\fP list from this platform. Volume can be removed only if no export is defined on it.
.TP
\fB\-E\fP, \fB\-\-exportd \fP\fIhost
A running exportd hostname.

.\""" rozo export
.SH EXPORT TOPIC
.B rozo export
.I list\fP | \fIcreate\fP | \fIupdate\fP | \fIremove\fP | \fIget\fP | \fImount\fP | \fIumount\fP \fB\-E | \-\-exportd\fP \fIhost\fP 

.\" rozo export list
.SS list
.B rozo export list \fB\-E | \-\-exportd\fP \fIhost\fP 
.TP 
Display the list of the exports managed by this platform. 
.TP
\fB\-E\fP, \fB\-\-exportd \fP\fIhost
A running exportd hostname.

.SS create
.B rozo export create \fIvid\fP \fB\-E\fP | \fB--exportd\fP \fIhost\fP [\fB\-n\fP | \fP\-\-name\fP\fI name\fP] [\fB\-p\fP | \fB--passwd\fP\fI password\fP] [\fB\-s\fP | \fB--squota\fP\fI squota\fP] [\fB\-a\fP | \fB--hquota\fP\fI hquota\fP]
.TP
Export a new filesytem on the given volume by \fIvid\fP.
.TP
\fB\-E\fP, \fB\-\-exportd \fP\fIhost
A running exportd hostname.
.TP
\fB\-n\fP, \fB\-\-name \fP\fIname
The name to give to the new export. If not set a name will be generated (export_x).
.TP
\fB\-p\fP, \fB\-\-passwd \fP\fIpasswd
Password to set.
.TP
\fB\-s\fP, \fB\-\-squota \fP\fIsquota
Soft quota to set. (value [K | M | G]) 
.TP
\fB\-a\fP, \fB\-\-hquota \fP\fIhquota
Hard quota to set. (value [K | M | G]) 

.SS update
.B rozo export update \fIeid\fP \fB\-E\fP | \fB--exportd\fP \fIhost\fP [\fB\-c\fP | \fB--current\fP\fI password\fP] [\fB\-p\fP | \fB--passwd\fP\fI password\fP] [\fB\-s\fP | \fB--squota\fP\fI squota\fP] [\fB\-a\fP | \fB--hquota\fP\fI hquota\fP]
.TP
Update an export according to \fIeid\fP.
.TP
\fB\-E\fP, \fB\-\-exportd \fP\fIhost
A running exportd hostname.
.TP
\fB\-c\fP, \fB\-\-current \fP\fIpasswd
Current password (needed with \fB-p\fP).
.TP
\fB\-p\fP, \fB\-\-passwd \fP\fIpasswd
Password to set.
.TP
\fB\-s\fP, \fB\-\-squota \fP\fIsquota
Soft quota to set. (value [K | M | G]) 
.TP
\fB\-a\fP, \fB\-\-hquota \fP\fIhquota
Hard quota to set. (value [K | M | G]) 

.SS remove
.B rozo export remove [\fB\-f\fP | \fB--force\fP] \fIeid\fP... \fB\-E\fP | \fB--exportd\fP \fIhost\fP
.TP
Remove an export according to \fIeid\fP... Only empty exports will be removed. 
.TP
\fB\-E\fP, \fB\-\-exportd\fP \fIhost\fP
A running exportd hostname.
.TP
\fB\-f\fP, \fB\-\-force 
Force removing non empty exports.

.SS mount
.B rozo export mount \fB\-E\fP | \fB--exportd\fP\fI host\fP [\fB\-n\fP | \fB--node\fP \fInode\fP...] [\fB\-e\fP | \fB--eids\fP \fIeid\fP...]
.TP
Mount export(s) identified by \fIeid\fP... on nodes.
.TP
\fB\-E\fP, \fB\-\-exportd \fP\fIhost
A running exportd hostname.
.TP
\fB\-n\fP, \fB\-\-nodes \fP\fInode\fP...
List of \fInode\fP hostnames to mount on. If not set exports will be mount on each node.
.TP
\fB\-e\fP, \fB\-\-eids \fP\fIeid\fP...
List of export(s) identified by \fIeid\fP... to mount.

.SS umount
.B rozo export umount \fB\-E\fP | \fB--exportd\fP \fIhost\fP [\fB\-n\fP | \fB--node\fP \fBnode\fP...] [\fB\-e\fP | \fB--eids\fP \fIeid\fP...]
.TP
Umount export(s) identified by \fIeid\fP... on nodes. 
.TP
\fB\-E\fP, \fB\-\-exportd \fP\fInode
A running exportd hostname.
.TP
\fB\-n\fP, \fB\-\-nodes \fP\fInode\fP...
List of \fInode\fP hostnames to umount from. If not set exports will be umount
from each node.
.TP
\fB\-e\fP, \fB\-\-eids \fP\fIeid\fP...
List of export(s) identified by \fIeid\fP... to umount.


.\""" rozo storage
.SH STORAGE TOPIC
.B rozo storage
.I list\fP | \fIget\fP | \fIadd\fP | \fIremove\fP \fB\-E | \-\-exportd\fP \fIhost\fP

.\" rozo storage list
.SS list
.B rozo storage list \fB\-E | \-\-exportd\fP \fIhost\fP 
.TP 
Display the list of the storage interface listeners.
.TP
\fB\-E\fP, \fB\-\-exportd \fP\fIhost
A running exportd hostname.

.\" rozo storage get
.SS get
.B rozo storage get \fInode\fP... \fB\-E | \-\-exportd\fP \fIhost\fP 
.TP 
Get the interface listeners for the given storage \fInode\fP hostnames.
.TP
\fB\-E\fP, \fB\-\-exportd \fP\fIhost
A running exportd hostname.

.\" rozo storage add
.SS add
.B rozo storage add \fB\-n\fP | \fB\-\-nodes\fP \fInode\fP... \fB\-i\fP | \fB\-\-interface\fP \fIinterface\fP \fB\-p\fP | \fB\-\-port\fP \fIport\fP \fB\-E\fP | \fB\-\-exportd\fP \fIhost\fP 
.TP
Add an interface listener according to the given \fIinterface\fP and
\fIport\fP to the storaged \fIhost\fP.
.TP
\fB\-E\fP, \fB\-\-exportd\fP \fIhost\fP
A running exportd hostname.
.TP
\fB\-n\fP, \fB\-\-nodes\fP \fInode\fP...
The list of running storaged nodes to add the new listener.
.TP
\fB\-i\fP, \fB\-\-interface\fP \fIinterface
Interface to set.
.TP
\fB\-p\fP, \fB\-\-port\fP \fIport
Port to set.

.\" rozo storage remove
.SS remove
.B rozo storage remove \fB\-n\fP | \fB\-\-nodes\fP \fInode\fP... \fB\-i\fP | \fB\-\-interface\fP \fIinterface\fP \fB\-p\fP | \fB\-\-port\fP \fIport\fP \fB\-E\fP | \fB\-\-exportd\fP \fIhost\fP 
.TP
Remove an interface listener to the storaged \fInode\fP list according to the given \fIinterface\fP and \fIport\fP.
.TP
\fB\-E\fP, \fB\-\-exportd\fP \fIhost\fP
A running exportd hostname.
.TP
\fB\-n\fP, \fB\-\-nodes\fP \fInode\fP...
The list of running storaged nodes to add the new listener.
.TP
\fB\-i\fP, \fB\-\-interface\fP \fIinterface
Interface to set.
.TP
\fB\-p\fP, \fB\-\-port\fP \fIport
Port to set.
.TP

.SH "REPORTING BUGS"
Report bugs to <bugs@fizians.org>.


.SH COPYRIGHT
Copyright (c) 2013 Fizians SAS. <http://www.fizians.com>

Rozofs is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published
by the Free Software Foundation, version 2.

Rozofs is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.


.SH AUTHOR
Fizians <http://www.fizians.org>


.SH "SEE ALSO"
.BR rozofs (7),
.BR exportd (8),
.BR storaged (8)
.BR rozofsmount (8)
