.\" Process this file with
.\" groff -man -Tascii rozolauncher.8
.\"
.TH rozolauncher 8 "JUNE 2014" Rozofs "User Manuals"
.SH NAME
rozolauncher \- rozofs process launcher tool
.SH SYNOPSIS
.B rozolauncher
.I start pid_file cmd
.RS
.RE
.B rozolauncher
.I stop  pid_file
.B
.SH DESCRIPTION
.B rozolauncher
is a utility to start or stop a RozoFS filesystem process. 
When the process is started with rozolauncher, it is restarted in case it crashes.
.SH OPTIONS
.IP "pid_file"
.RS
is the absolute path name of a file that contains the pid of the launcher process. It has to be unique per launched process. 
.RE
.IP "cmd"
.RS
.I cmd
is the executable name followed by the arguments of the process to start.
.RE
.\".SH ENVIRONMENT
.\".SH DIAGNOSTICS
.SH "REPORTING BUGS"
Report bugs to <bugs@fizians.org>.
.SH COPYRIGHT
Copyright (c) 2013 Fizians SAS. <http://www.fizians.com>

Rozofs is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published
by the Free Software Foundation, version 2.

Rozofs is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
.SH AUTHOR
Fizians <http://www.fizians.org>
.SH "SEE ALSO"
.BR rozofs (7),
