.\" Process this file with
.\" groff -man -Tascii storage.conf.5
.\"
.TH STORAGE.CONF 5 "SEPTEMBER 2013" Rozofs "User Manuals"
.SH NAME
storage.conf \- RozoFS storage daemon configuration file
.SH DESCRIPTION
.B "storage.conf"
is manage throw 
.B libconfig
<http://www.hyperrealm.com/libconfig/> and thus complies to the
.B libconfig
grammar.

.SS threads (optional)

Specifies number of threads that can process the disk requests. (default: 2)

.SS nbcores (optional)

Maximum number of core files to keep. (default: 2)

.SS listen (mandatory)

Specifies list of IP(s) (or hostname(s)) and port(s) the storio process should listen on for receive write and read requests from clients.

    addr: (IP or hostname that the server should listens on)
            - must be a valid IPv4 address or a valid hostname.
            - if "*" is specified storio will listen on any of the interfaces.

    port: (TCP port number (in decimal) to use for storio process)

.SS storages (mandatory)

It's the list of local storage managed by this storaged.
Each storage is identified by the cluster to which belongs the storage (cid) 
and by it's identifier in the cluster (sid). Each pair (cid,sid) must be
unique. The root is the path where will be stored data for this storage.

    cid: (cluster identifier)
            - must be an integer.
            - should exist in exportd configuration file.

    sid: (storage identifier)
            - must be an integer (between 1 and 255).
            - should exist in exportd configuration file.

    root: (directory path where data will be stored)
            - must be an existing directory.
            - must be unique for each storage managed by this storaged.


.SH EXAMPLE
.PP
.nf
.ta +3i
# sample RozoFS storage configuration file

listen = (
    {addr = "192.168.1.1"; port = 41001; },
    {addr = "192.168.2.1"; port = 41001; }
);

storages = (
    {cid = 1; sid = 1; root = "/path/to/foo";},
    {cid = 1; sid = 2; root = "/path/to/bar";},
    {cid = 2; sid = 1; root = "/path/to/baz";}
 );

.SH FILES
.I /etc/rozofs/storage.conf (/usr/local/etc/rozofs/storage.conf)
.RS
The system wide configuration file.
.\".SH ENVIRONMENT
.\".SH DIAGNOSTICS
.\".SH BUGS
.SH AUTHOR
Fizians <http://www.fizians.com>
.SH "SEE ALSO"
.BR rozofs (7),
.BR storaged (8)
