.\" Process this file with
.\" groff -man -Tascii storage.conf.5
.\"
.TH STORAGE.CONF 5 "MAY 2013" Rozofs "User Manuals"
.SH NAME
storage.conf \- rozofs storage daemon configuration file
.SH DESCRIPTION
.B "storage.conf"
is manage throw 
.B libconfig
<http://www.hyperrealm.com/libconfig/> and thus complies to the
.B libconfig
grammar.

.SS ports

It's a list of TCP ports used for receive write and read requests from clients (rozofsmount).
A process will be created for each TCP port.
Another process will be created to receive other requests.

.SS storages

It's the list of local storage managed by this storaged.
Each storage is identified by the cluster to which belongs the storage (cid) 
and by it's identifier in the cluster (sid). Each pair (cid,sid) must be
unique. The root is the path where will be stored data for this storage.

    cid: (cluster identifier)
            - must be an integer.
            - should exist in exportd configuration file.

    sid: (storage identifier)
            - must be an integer (between 1 and 255).
            - should exist in exportd configuration file.

    root: (directory path where data will be stored)
            - must be an existing directory.
            - must be unique for each storage managed by this storaged.


.SH EXAMPLE
.PP
.nf
.ta +3i
# sample /etc/rozofs/storage.conf file

ports = [40001, 40002, 40003, 40004];  

storages = (
    {cid = 1; sid = 1; root = "/path/to/foo";},
    {cid = 1; sid = 2; root = "/path/to/bar";},
    {cid = 2; sid = 1; root = "/path/to/baz";}
 );

.SH FILES
.I /etc/rozofs/storage.conf (/usr/local/etc/rozofs/storage.conf)
.RS
The system wide configuration file.
.\".SH ENVIRONMENT
.\".SH DIAGNOSTICS
.\".SH BUGS
.SH AUTHOR
Fizians <http://www.fizians.com>
.SH "SEE ALSO"
.BR rozofs (7),
.BR storaged (8)
