.\" Process this file with
.\" groff -man -Tascii storage_rebuild.8
.\"
.TH storaged_rebuild 8 "JUNE 2014" RozoFS "User Manuals"
.SH NAME
storaged_rebuild \- RozoFS storage rebuild process
.SH SYNOPSIS
.B storaged_rebuild 
[
.I options
] 
.B
.SH DESCRIPTION
.B storaged_rebuild
rebuilds either a file, or a device, or all devices of a storage node.
.SH OPTIONS
.IP "-h, --help"
.RS
Print help.
.RE
.IP "-c, --config file"
.RS
Use 
.I file
as configuration file. default is
.I /etc/rozofs/storage.conf
(or
.I /usr/local/etc/rozofs/storage.conf
according to install options)
.RE
.IP "-r, --rebuild export_host"
.RS
Use
.I export_host
as the list of addresses (or dns names) where exportd daemon is running. When securing the exportd thanks to virtual IP address only the virtual IP address is declared (i.e "192.168.10.1"). When no virtual IP address is used the list of "physical" IP addresses of each host securing the exportd must be given (i.e "192.168.10.1/192.168.20.1"). 
.TP
.RE
.IP "-s, --sid cid/sid"
.RE
.RS
Rebuilds only the storage identifier 
.I sid
of cluster
.I cid.
Default behaviour is to rebuild every sid configured in the configuration file.
.RE
.IP "-d, --device device-number"
.RE
.RS
Rebuilds only 
.I device-number.
Default is to rebuild every device.
.RE
.IP "-f, --fid FID"
.RE
.RS
Rebuilds only the file identified by
.I FID.
In this case --sid option is mandatory and -d option is ignored.
.RE
.IP "-p, --parallel para"
.RE
.RS
Use 
.I para
processes in parallel for rebuilding. Default value is 4.
.RE
.SH FILES
.I /etc/rozofs/storage.conf (/usr/local/etc/rozofs/storage.conf)
.RS
The system wide configuration file. See
.BR storage.conf (5)
for further details.
.RE
.I /var/log/syslog
.RS
The log file. See
.BR syslogd (8)
and
.BR syslog.conf (5)
for further details.
.\".SH ENVIRONMENT
.\".SH DIAGNOSTICS
.SH "REPORTING BUGS"
Report bugs to <bugs@fizians.org>.
.SH COPYRIGHT
Copyright (c) 2013 Fizians SAS. <http://www.fizians.com>

Rozofs is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published
by the Free Software Foundation, version 2.

Rozofs is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
.SH AUTHOR
Fizians <http://www.fizians.org>
.SH "SEE ALSO"
.BR rozofs (7),
.BR storage.conf (5),
.BR exportd (8),
.BR rozofsmount (8)
