/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "geo_replica_proto.h"
#include <rozofs/rozofs.h>

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

void *
geo_null_1(void *argp, CLIENT *clnt)
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, GEO_NULL,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return ((void *)&clnt_res);
}

geo_sync_req_ret_t *
geo_sync_req_1(geo_sync_req_arg_t *argp, CLIENT *clnt)
{
	static geo_sync_req_ret_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, GEO_SYNC_REQ,
		(xdrproc_t) xdr_geo_sync_req_arg_t, (caddr_t) argp,
		(xdrproc_t) xdr_geo_sync_req_ret_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

geo_sync_req_ret_t *
geo_sync_get_next_req_1(geo_sync_get_next_req_arg_t *argp, CLIENT *clnt)
{
	static geo_sync_req_ret_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, GEO_SYNC_GET_NEXT_REQ,
		(xdrproc_t) xdr_geo_sync_get_next_req_arg_t, (caddr_t) argp,
		(xdrproc_t) xdr_geo_sync_req_ret_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

geo_status_ret_t *
geo_sync_delete_req_1(geo_sync_delete_req_arg_t *argp, CLIENT *clnt)
{
	static geo_status_ret_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, GEO_SYNC_DELETE_REQ,
		(xdrproc_t) xdr_geo_sync_delete_req_arg_t, (caddr_t) argp,
		(xdrproc_t) xdr_geo_status_ret_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

geo_status_ret_t *
geo_sync_close_req_1(geo_sync_close_req_arg_t *argp, CLIENT *clnt)
{
	static geo_status_ret_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, GEO_SYNC_CLOSE_REQ,
		(xdrproc_t) xdr_geo_sync_close_req_arg_t, (caddr_t) argp,
		(xdrproc_t) xdr_geo_status_ret_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
