/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "geo_replica_proto.h"
#include <rozofs/rozofs.h>

bool_t
xdr_geo_status_t (XDR *xdrs, geo_status_t *objp)
{
	//register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_geo_sync_req_arg_t (XDR *xdrs, geo_sync_req_arg_t *objp)
{
	//register int32_t *buf;

	 if (!xdr_uint16_t (xdrs, &objp->eid))
		 return FALSE;
	 if (!xdr_uint16_t (xdrs, &objp->site_id))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->local_ref))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_geo_sync_data_ret_t (XDR *xdrs, geo_sync_data_ret_t *objp)
{
	//register int32_t *buf;

	 if (!xdr_uint16_t (xdrs, &objp->eid))
		 return FALSE;
	 if (!xdr_uint16_t (xdrs, &objp->site_id))
		 return FALSE;
	 if (!xdr_uint64_t (xdrs, &objp->file_idx))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->local_ref))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->remote_ref))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->last))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->first_record))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->nb_records))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->data.data_val, (u_int *) &objp->data.data_len, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_geo_sync_req_ret_t (XDR *xdrs, geo_sync_req_ret_t *objp)
{
	//register int32_t *buf;

	 if (!xdr_geo_status_t (xdrs, &objp->status))
		 return FALSE;
	switch (objp->status) {
	case GEO_SUCCESS:
		 if (!xdr_geo_sync_data_ret_t (xdrs, &objp->geo_sync_req_ret_t_u.data))
			 return FALSE;
		break;
	case GEO_FAILURE:
		 if (!xdr_int (xdrs, &objp->geo_sync_req_ret_t_u.error))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_geo_sync_get_next_req_arg_t (XDR *xdrs, geo_sync_get_next_req_arg_t *objp)
{
	//register int32_t *buf;

	 if (!xdr_uint16_t (xdrs, &objp->eid))
		 return FALSE;
	 if (!xdr_uint16_t (xdrs, &objp->site_id))
		 return FALSE;
	 if (!xdr_uint64_t (xdrs, &objp->file_idx))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->local_ref))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->remote_ref))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->next_record))
		 return FALSE;
	 if (!xdr_uint64_t (xdrs, &objp->status_bitmap))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_geo_sync_delete_req_arg_t (XDR *xdrs, geo_sync_delete_req_arg_t *objp)
{
	//register int32_t *buf;

	 if (!xdr_uint16_t (xdrs, &objp->eid))
		 return FALSE;
	 if (!xdr_uint16_t (xdrs, &objp->site_id))
		 return FALSE;
	 if (!xdr_uint64_t (xdrs, &objp->file_idx))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->local_ref))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->remote_ref))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_geo_sync_close_req_arg_t (XDR *xdrs, geo_sync_close_req_arg_t *objp)
{
	//register int32_t *buf;

	 if (!xdr_uint16_t (xdrs, &objp->eid))
		 return FALSE;
	 if (!xdr_uint16_t (xdrs, &objp->site_id))
		 return FALSE;
	 if (!xdr_uint64_t (xdrs, &objp->file_idx))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->local_ref))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->remote_ref))
		 return FALSE;
	 if (!xdr_uint64_t (xdrs, &objp->status_bitmap))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_geo_status_ret_t (XDR *xdrs, geo_status_ret_t *objp)
{
	//register int32_t *buf;

	 if (!xdr_geo_status_t (xdrs, &objp->status))
		 return FALSE;
	switch (objp->status) {
	case GEO_FAILURE:
		 if (!xdr_int (xdrs, &objp->geo_status_ret_t_u.error))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}
