/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _GWPROTO_H_RPCGEN
#define _GWPROTO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#include <rozofs/rozofs.h>

enum gw_status_e {
	GW_FAILURE = 0,
	GW_SUCCESS = 1,
};
typedef enum gw_status_e gw_status_e;

struct gw_header_t {
	uint32_t export_id;
	uint32_t nb_srv;
	uint32_t srv_rank;
};
typedef struct gw_header_t gw_header_t;

struct gw_status_t {
	gw_status_e status;
	union {
		int error;
	} gw_status_t_u;
};
typedef struct gw_status_t gw_status_t;

struct gw_dirty_section_t {
	uint32_t absolute_idx;
	uint32_t section_sz;
	struct {
		u_int bitmap_len;
		uint8_t *bitmap_val;
	} bitmap;
};
typedef struct gw_dirty_section_t gw_dirty_section_t;

struct gw_invalidate_sections_t {
	gw_header_t hdr;
	struct {
		u_int section_len;
		gw_dirty_section_t *section_val;
	} section;
};
typedef struct gw_invalidate_sections_t gw_invalidate_sections_t;

struct gw_configuration_t {
	gw_header_t hdr;
	uint32_t ipAddr;
	uint16_t port;
	struct {
		u_int eid_len;
		uint32_t *eid_val;
	} eid;
};
typedef struct gw_configuration_t gw_configuration_t;

#define GW_PROGRAM 0x20000009
#define GW_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define GW_NULL 0
extern  void * gw_null_1(void *, CLIENT *);
extern  void * gw_null_1_svc(void *, struct svc_req *);
#define GW_INVALIDATE_SECTIONS 1
extern  gw_status_t * gw_invalidate_sections_1(gw_invalidate_sections_t *, CLIENT *);
extern  gw_status_t * gw_invalidate_sections_1_svc(gw_invalidate_sections_t *, struct svc_req *);
#define GW_INVALIDATE_ALL 2
extern  gw_status_t * gw_invalidate_all_1(gw_header_t *, CLIENT *);
extern  gw_status_t * gw_invalidate_all_1_svc(gw_header_t *, struct svc_req *);
#define GW_CONFIGURATION 3
extern  gw_status_t * gw_configuration_1(gw_configuration_t *, CLIENT *);
extern  gw_status_t * gw_configuration_1_svc(gw_configuration_t *, struct svc_req *);
extern int gw_program_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GW_NULL 0
extern  void * gw_null_1();
extern  void * gw_null_1_svc();
#define GW_INVALIDATE_SECTIONS 1
extern  gw_status_t * gw_invalidate_sections_1();
extern  gw_status_t * gw_invalidate_sections_1_svc();
#define GW_INVALIDATE_ALL 2
extern  gw_status_t * gw_invalidate_all_1();
extern  gw_status_t * gw_invalidate_all_1_svc();
#define GW_CONFIGURATION 3
extern  gw_status_t * gw_configuration_1();
extern  gw_status_t * gw_configuration_1_svc();
extern int gw_program_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_gw_status_e (XDR *, gw_status_e*);
extern  bool_t xdr_gw_header_t (XDR *, gw_header_t*);
extern  bool_t xdr_gw_status_t (XDR *, gw_status_t*);
extern  bool_t xdr_gw_dirty_section_t (XDR *, gw_dirty_section_t*);
extern  bool_t xdr_gw_invalidate_sections_t (XDR *, gw_invalidate_sections_t*);
extern  bool_t xdr_gw_configuration_t (XDR *, gw_configuration_t*);

#else /* K&R C */
extern bool_t xdr_gw_status_e ();
extern bool_t xdr_gw_header_t ();
extern bool_t xdr_gw_status_t ();
extern bool_t xdr_gw_dirty_section_t ();
extern bool_t xdr_gw_invalidate_sections_t ();
extern bool_t xdr_gw_configuration_t ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_GWPROTO_H_RPCGEN */
