/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "gwproto.h"
#include <rozofs/rozofs.h>

bool_t
xdr_gw_status_e (XDR *xdrs, gw_status_e *objp)
{
	//register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_gw_header_t (XDR *xdrs, gw_header_t *objp)
{
	//register int32_t *buf;

	 if (!xdr_uint32_t (xdrs, &objp->export_id))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->nb_srv))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->srv_rank))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_gw_status_t (XDR *xdrs, gw_status_t *objp)
{
	//register int32_t *buf;

	 if (!xdr_gw_status_e (xdrs, &objp->status))
		 return FALSE;
	switch (objp->status) {
	case GW_FAILURE:
		 if (!xdr_int (xdrs, &objp->gw_status_t_u.error))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_gw_dirty_section_t (XDR *xdrs, gw_dirty_section_t *objp)
{
	//register int32_t *buf;

	 if (!xdr_uint32_t (xdrs, &objp->absolute_idx))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->section_sz))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->bitmap.bitmap_val, (u_int *) &objp->bitmap.bitmap_len, ~0,
		sizeof (uint8_t), (xdrproc_t) xdr_uint8_t))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_gw_invalidate_sections_t (XDR *xdrs, gw_invalidate_sections_t *objp)
{
	//register int32_t *buf;

	 if (!xdr_gw_header_t (xdrs, &objp->hdr))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->section.section_val, (u_int *) &objp->section.section_len, ~0,
		sizeof (gw_dirty_section_t), (xdrproc_t) xdr_gw_dirty_section_t))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_gw_configuration_t (XDR *xdrs, gw_configuration_t *objp)
{
	//register int32_t *buf;

	 if (!xdr_gw_header_t (xdrs, &objp->hdr))
		 return FALSE;
	 if (!xdr_uint32_t (xdrs, &objp->ipAddr))
		 return FALSE;
	 if (!xdr_uint16_t (xdrs, &objp->port))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->eid.eid_val, (u_int *) &objp->eid.eid_len, ~0,
		sizeof (uint32_t), (xdrproc_t) xdr_uint32_t))
		 return FALSE;
	return TRUE;
}
