/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "gwproto.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif
#include <rozofs/rozofs.h>
#define GW_NAME_LEN (ROZOFS_HOSTNAME_MAX/4)
//  uint32_t           eid[EXPGW_EID_MAX_IDX];  
//  gw_host_conf_t     gateway_host[EXPGW_EXPGW_MAX_IDX];

void
gw_program_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		gw_invalidate_sections_t gw_invalidate_sections_1_arg;
		gw_header_t gw_invalidate_all_1_arg;
		gw_configuration_t gw_configuration_1_arg;
		gw_header_t gw_poll_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case GW_NULL:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) gw_null_1_svc;
		break;

	case GW_INVALIDATE_SECTIONS:
		_xdr_argument = (xdrproc_t) xdr_gw_invalidate_sections_t;
		_xdr_result = (xdrproc_t) xdr_gw_status_t;
		local = (char *(*)(char *, struct svc_req *)) gw_invalidate_sections_1_svc;
		break;

	case GW_INVALIDATE_ALL:
		_xdr_argument = (xdrproc_t) xdr_gw_header_t;
		_xdr_result = (xdrproc_t) xdr_gw_status_t;
		local = (char *(*)(char *, struct svc_req *)) gw_invalidate_all_1_svc;
		break;

	case GW_CONFIGURATION:
		_xdr_argument = (xdrproc_t) xdr_gw_configuration_t;
		_xdr_result = (xdrproc_t) xdr_gw_status_t;
		local = (char *(*)(char *, struct svc_req *)) gw_configuration_1_svc;
		break;

	case GW_POLL:
		_xdr_argument = (xdrproc_t) xdr_gw_header_t;
		_xdr_result = (xdrproc_t) xdr_gw_status_t;
		local = (char *(*)(char *, struct svc_req *)) gw_poll_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}
