/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "stcpproto.h"
#include <rozofs/rozofs.h>

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

void *
stcpp_null_1(void *argp, CLIENT *clnt)
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, STCPP_NULL,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return ((void *)&clnt_res);
}

stcpp_profiler_ret_t *
stcpp_get_profiler_1(void *argp, CLIENT *clnt)
{
	static stcpp_profiler_ret_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, STCPP_GET_PROFILER,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_stcpp_profiler_ret_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

stcpp_status_ret_t *
stcpp_clear_1(void *argp, CLIENT *clnt)
{
	static stcpp_status_ret_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, STCPP_CLEAR,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_stcpp_status_ret_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
